-- Batch 36 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'The Trim Saw Attachment for the CabKing 8 Inch Grinder Polisher adds saw capability to the machine.

It includes an 8 in sintered blade, plastic blade guard, drip pan and support, splash guards, a saw platform and a second platform for small rough stone.', features = '["8\\" sintered blade", "Plastic blade guard", "Drip pan", "Pan support", "Splash guards", "Saw platform", "Additional platform for small rough stone"]', included = '["8\\" sintered blade", "Plastic blade guard", "Drip pan and support", "Splash guards", "Saw platform"]', specs = '{}', warranty = NULL WHERE id = 'trim-saw-attachment-for-cabking-8-inch-grinder-polisher';
UPDATE products SET blurb = 'The Trim Saw Attachment for the CabKing 6 Inch Grinder Polisher adds a trim saw to the machine.

It includes an 8 in sintered blade, plastic blade guard, drip pan with support, splash guards and a dual-platform setup: a saw platform plus a second platform for small rough stone.', features = '["8\\" sintered blade", "Plastic blade guard", "Drip pan", "Pan support", "Splash guards", "Saw platform", "Additional platform for small rough stone"]', included = '["8\\" sintered blade", "Plastic blade guard", "Drip pan with support", "Splash guards", "Dual platforms for different stone sizes"]', specs = '{}', warranty = NULL WHERE id = 'trim-saw-attachment-for-cabking-6-inch-grinder-polisher';
UPDATE products SET blurb = 'The CabKing 6 Inch Grinder Polisher is a six-wheel, two-end-station cabbing machine driven by a 1/4 hp, 1800 rpm direct-drive motor.

A shut-off valve above each wheel controls water station by station, a clean-water system prevents cross-contamination between grits, and a 6W, 12V lamp lights the work. Two 6 x 1-1/2 in metal-bond diamond wheels (80 and 220 grit) and resin-bond wheels are included. It measures 31 x 16 x 15 in and weighs 56 lb. The motor and parts carry a one-year warranty (wheels not covered).', features = '["Direct Drive, 110/115V, 1/4 hp, 1800 rpm motor", "Individual water shut off valves above each wheel and grinding/polishing pad", "6 wheels and 2 end stations", "Clean water system provides contamination free work stations", "6W, 12V lamp", "Aluminum splash hoods with adjustable clear splash shields", "Plastic pans with drain holes", "Side splash guards", "Metal hand rests"]', included = '["Two 6\\" x 1-1/2\\" metal bonded diamond wheels (80 and 220 grit)", "Four 6\\" x 1-1/2\\" resin bonded diamond wheels (280, 600, 1200, and 3000 grit)", "One 6\\" no-hole diamond flat lap (320 grit)", "One 6\\" no-hole canvas polishing pad", "One 2-gram syringe of diamond paste compound (14,000 grit)", "Goggles and apron", "Separate 605 GPH, 30W submersible pump"]', specs = '{"Weight": "56 lb", "Width": "31\\"", "Height": "15\\"", "Depth": "16\\""}', warranty = '1 Year manufacturer\'s warranty on motor and parts (wheels not covered)' WHERE id = 'cabking-6-inch-grinder-polisher';
UPDATE products SET blurb = 'The Covington Glass Lathe Number Two is a 1 hp glass lathe with a turned, ground and polished 1 in steel shaft to keep vibration down.

It has three speeds, starting at 635 and 805 rpm, a quick-belt-change motor mount, and steel and cast aluminum construction on an aluminum-topped Lam-I-Cushion base. A water manifold and 36 in of Loc-Line tubing are included. It measures 39 x 39 x 17 in and weighs 102 lb. Manufacturer\'s warranty applies.', features = '["Turned, ground, and polished 1\\" steel shaft minimizes vibration", "1 hp motor", "Runs quietly", "Aluminum-topped Lam-I-Cushion base", "Heavy-duty steel and cast aluminum construction", "Quick-belt-change motor mount", "Three speeds: 635, 805, and 1100 rpm", "Heavy duty sealed ball bearings greased for life", "Optional 1-1/2\\" steel tube stand with anchor holes"]', included = '["Water manifold", "36\\" of Loc-Line tubing"]', specs = '{"Weight": "102 lb", "Width": "39\\"", "Height": "17\\"", "Depth": "39\\""}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-glass-lathe-number-two';
UPDATE products SET blurb = 'The Covington Original Glass Lathe is a 1 hp lathe with a turned, ground and polished 1 in steel shaft and three speeds: 635, 805 and 1100 rpm.

It comes with two powder-coated splash pans and hoods, two felt guards, a water manifold and 36 in of Loc-Line tubing. A quick-belt-change motor mount speeds speed changes. It measures 37 x 32 x 15 in and weighs 200 lb. Manufacturer\'s warranty applies.', features = '["1\\" turned, ground, and polished steel shaft minimizes vibration", "Three speeds: 635, 805, and 1100 rpm", "Two powder coated splash pans and hoods", "Two felt guards", "1 hp motor", "Quick-belt-change motor mount", "Heavy-duty, sealed ball bearings greased for life", "Runs quietly", "Accommodates wheels up to 10\\"", "Aluminum-topped Lam-I-Cushion base", "Heavy duty steel and cast aluminum construction", "Two 4\\" spacers"]', included = '["Water manifold", "36\\" of loc-line tubing"]', specs = '{"Weight": "200 lb", "Width": "37\\"", "Height": "15\\"", "Depth": "32\\""}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-original-glass-lathe';
UPDATE products SET blurb = 'The Covington 16 Inch Cork and Felt Glass Polisher is a 1/3 hp glass polisher with a spray-nozzle back plate, rust-resistant powder-coated pans and an adjustable sponge bench to limit splash.

The tank comes off for quick wheel changes, and the ball bearings are neoprene-sealed and greased for life. It ships with a 16 x 3 in cork wheel, a 16 x 3 in felt wheel and instructions. It measures 37 x 26 x 26 in and weighs 140 lb. Manufacturer\'s warranty applies.', features = '["Back plate with spray nozzle", "Powder coated pans resist rust", "Adjustable sponge bench to minimize splash", "Removable tank for easy wheel change", "Heavy duty ball bearings, neoprene sealed and greased for life", "Belt guard", "1/3 hp high-torque motor", "Instructions included"]', included = '["One 16\\" x 3\\" cork wheel", "One 16\\" x 3\\" felt wheel", "Instructions"]', specs = '{"Weight": "140 lb", "Width": "37\\"", "Height": "26\\"", "Depth": "26\\""}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-16-inch-cork-and-felt-glass-polisher';
UPDATE products SET blurb = 'The Covington 10 Inch Cork and Felt Glass Polisher comes with a cork wheel and a felt wheel already dressed and ready to use.

A spray-nozzle back plate, rust-resistant powder-coated pans and an adjustable sponge bench keep splash down, and the side panels come off for wheel changes. It measures 25 x 25 x 20 in and weighs 92 lb, with instructions and the manufacturer\'s warranty.', features = '["Back plate with spray nozzle", "Powder coated pans resist rust", "Adjustable sponge bench to minimize splash", "Removable side panels for easy wheel change", "Comes with cork and felt wheels, dressed and ready to use", "Turned, ground and polished 1\\" shaft", "Heavy duty ball bearings, neoprene sealed and greased for life", "Heavy duty steel and cast aluminum construction", "1/3 hp high-torque motor", "Runs quietly", "Instructions included"]', included = '["Cork wheel", "Felt wheel", "Instructions"]', specs = '{"Weight": "92 lb", "Width": "25\\"", "Height": "20\\"", "Depth": "25\\""}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-10-inch-cork-and-felt-glass-polisher';
UPDATE products SET blurb = 'Covington Nickel Bonded Diamond Cones are for grinding inside curves and bottles.

Each is roughly 3 in across the base and 3 in tall, with a 3/16 in center hole for through-shaft water systems. Female threads are 1-14 or 5/8-11.', features = '["For bottles and inside curves", "3/16\\" center hole for through-shaft water systems"]', included = '[]', specs = '{"Size": "approx. 3\\" base x 3\\" height", "Thread sizes": "1\\"-14 female, 5/8\\"-11 female", "Grits": "Coarse (100g), Medium (220g), Fine (600g)"}', warranty = NULL WHERE id = 'covington-nickel-bonded-diamond-cones';
UPDATE products SET blurb = 'Covington Resin Bonded Diamond Smoothing Domes cut less aggressively than the nickel-bonded domes, which suits edge work and pre-polishing on curved surfaces.

Each is roughly 4 in across the base and 2.5 in tall, with a 1-14 RH or 5/8-11 RH female thread.', features = '["Less aggressive action than nickel bonded domes", "Good for edge work and pre-polishing curved surfaces"]', included = '[]', specs = '{"Size": "approx. 4\\" base x 2.5\\" height", "Thread sizes": "1\\"-14RH female, 5/8\\"-11RH female", "Grits": "100, 220, 325, 600, 1200"}', warranty = NULL WHERE id = 'covington-resin-bonded-diamond-smoothing-domes';
UPDATE products SET blurb = 'Covington Resin Bond Magnetic Backed Diamond Discs have a relaxed resin bond suited to pre-polishing, and swap on and off quickly thanks to the magnetic backing.

Sizes are 8, 10, 12, 18 and 24 in, with grits from 100 to 100,000 and hole options of none, 1/4 in or 1 in.', features = '["Magnetic backed", "Super-fast to change", "Relaxed resin bond suited to pre-polishing"]', included = '[]', specs = '{"Sizes": "8\\", 10\\", 12\\", 18\\", 24\\"", "Grits": "100-100000", "Hole sizes": "No hole, 1/4\\", 1\\""}', warranty = NULL WHERE id = 'covington-resin-bond-magnetic-backed-diamond-discs';
