-- Batch 27 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'The Covington C-BRAND Edge Diamond Saw Blade is an ultra-thin, electroplated diamond blade made in the USA.

It comes in 6 in and 10 in sizes, in thicknesses of 0.012, 0.015 and 0.020 in, with a 5/8 in or 1/2 in arbor.', features = '["Ultra thin design", "Electroplated diamond coating", "Made in the USA", "Available in 6\\" and 10\\" sizes", "Thickness options: 0.012\\", 0.015\\", 0.020\\"", "Arbor options: 5/8\\", 1/2\\""]', included = '[]', specs = '{"Sizes": "6\\", 10\\"", "Thickness": "0.012\\", 0.015\\", 0.020\\"", "Arbor": "5/8\\", 1/2\\""}', warranty = NULL WHERE id = 'covington-c-brand-edge-diamond-saw-blade';
UPDATE products SET blurb = 'Covington Ultimate Glass Diamond Saw Blades cut glass quickly with minimal chipping, using fine 100 grit diamond and a 0.095 in kerf.

A 1 in to 5/8 in bushing comes with the blade, and a 1/2 in bushing is available.', features = '["Minimal chipping", "Fine grade 100 grit diamond", "Cuts quickly", "Superior finish", "0.095\\" kerf", "Comes with a 1\\"-5/8\\" bushing", "1/2\\" bushing available"]', included = '["1\\"-5/8\\" bushing"]', specs = '{"Kerf": "0.095\\"", "Grit": "100"}', warranty = NULL WHERE id = 'covington-ultimate-glass-diamond-saw-blades';
UPDATE products SET blurb = 'The Sanding Belt Starter Kit gives you 10 sanding belts covering grits from 60 to 1,000, including one each of 60, 80 and 220 and two of 100, plus finer grits.

It is offered in four belt sizes: 2-1/2 x 6 in (for 6 in expandable drums), 3 x 24 in (Covington 464 and 466), 3 x 8 in (for 8 in expandable drums) and a fourth larger size.', features = '["10 sanding belts included", "Grits from 60 to 1,000", "Available in 4 belt dimensions"]', included = '["One 60 grit belt", "One 80 grit belt", "Two 100 grit belts", "One 220 grit belt", "One 320 grit belt", "One 400 grit belt", "One 600 grit belt", "One 800 grit belt", "One 1,000 grit belt"]', specs = '{"Sizes": "2-1/2\\" x 6\\" (6\\" expandable drums), 3\\" x 24\\" (Covington 464 & 466), 3\\" x 8\\" (8\\" expandable drums and Covington 460), 3\\" x 41-1/2\\" (Covington 760, 761, 762)"}', warranty = NULL WHERE id = 'sanding-belt-starter-kit';
UPDATE products SET blurb = 'Felt Polishing Belts are woolen felt belts that give an optical polish when used with cerium oxide.

They come in four sizes to fit various sanders and drums, including 2-1/2 x 6 in for 6 in expandable drums and 3 x 24 in for Covington 464 and 466 sanders.', features = '["High-quality woolen felt", "Works with cerium oxide for optical polish", "Available in 4 sizes to fit various sanders and drums"]', included = '[]', specs = '{"Sizes": "2-1/2\\" x 6\\" (6\\" expandable drums), 3\\" x 24\\" (Covington 464 & 466), 3\\" x 8\\" (8\\" expandable drums and Covington 460), 3\\" x 41-1/2\\" (Covington 760, 761, 762)"}', warranty = NULL WHERE id = 'felt-polishing-belts';
UPDATE products SET blurb = 'Diamond Sander Belts are resin-bond diamond belts that keep cutting for a long time, color-coded by grit: 100 black, 220 purple, 325 brown, 600 red, 800 green and 1200 blue.

They come in four sizes to fit various sanders and drums, including 2-1/2 x 6 in for 6 in expandable drums and 3 x 24 in for Covington 464 and 466 sanders.', features = '["Long lasting belt life", "Resin bond", "Grit options: 100 Black, 220 Purple, 325 Brown, 600 Red, 800 Green, 1200 Blue", "Available in 4 sizes to fit various sanders and drums"]', included = '[]', specs = '{"Sizes": "2-1/2\\" x 6\\" (6\\" expandable drums), 3\\" x 24\\" (Covington 464 & 466), 3\\" x 8\\" (8\\" expandable drums and Covington 460), 3\\" x 41-1/2\\" (Covington 760, 761, 762)", "Grits": "100, 220, 325, 600, 800, 1200"}', warranty = NULL WHERE id = 'diamond-sander-belts';
UPDATE products SET blurb = 'Cork Belts are used for pre-polishing and final polishing of glass. With 2-F pumice they leave a hazy finish.

They come in four sizes to fit various sanders and drums, including 2-1/2 x 6 in for 6 in expandable drums and 3 x 24 in for Covington 464 and 466 sanders.', features = '["Ideal for pre-polishing and final polishing glass", "Used with pumice (2-F) for a hazy finish", "Available in 4 sizes to fit various sanders and drums"]', included = '[]', specs = '{"Sizes": "2-1/2\\" x 6\\" (6\\" expandable drums), 3\\" x 24\\" (Covington 464 & 466), 3\\" x 8\\" (8\\" expandable drums and Covington 460), 3\\" x 41-1/2\\" (Covington 760, 761, 762)"}', warranty = NULL WHERE id = 'cork-belts';
UPDATE products SET blurb = 'Covington Thin Rim Saw Blades are affordable, fast-cutting blades in 4, 5 and 6 in diameters, with .006 in or .010 in rim thickness.

The arbor hole is 5/8 in and a 1/2 in bushing is included.', features = '["High quality", "Fast cutting", "High-yield", "Affordable", "5/8\\" arbor hole", "1/2\\" bushing included"]', included = '["1/2\\" bushing"]', specs = '{"Diameters": "4\\", 5\\", 6\\"", "Rim thickness": ".006\\" and .010\\" options"}', warranty = NULL WHERE id = 'covington-thin-rim-saw-blades';
UPDATE products SET blurb = 'Covington Red Sintered Diamond Saw Blades are thin-rim blades with 325/400 diamond grit for fine cutting in general stone work.

The sintered construction lasts longer than a notched-rim blade. Sizes start at 4 in (.023 in rim), 5 in (.015 in rim) and 6 in (.020 in rim), for 5/8 in to 1/2 in arbors.', features = '["Sintered diamond construction with 325/400 diamond grit", "Longer lasting than notched rim blades", "Fine cutting capability", "Thin-rim design for general stone work"]', included = '[]', specs = '{"4\\"": "0.023\\" rim, 5/8\\"-1/2\\" arbor", "5\\"": "0.015\\" rim, 5/8\\"-1/2\\" arbor", "6\\"": "0.020\\" rim, 5/8\\"-1/2\\" arbor", "8\\"": "0.031\\" rim, 5/8\\"-1/2\\" arbor", "10\\"": "0.038\\" rim, 5/8\\"-1/2\\" arbor", "12\\"": "0.042\\" rim, 5/8\\"-1/2\\" arbor", "14\\"": "0.045\\" rim, 5/8\\"-1/2\\" arbor"}', warranty = NULL WHERE id = 'covington-red-sintered-diamond-saw-blades';
UPDATE products SET blurb = 'Covington Black Sintered Diamond Saw Blades have a thick rim built to last, and are the best fit for agates and geodes.

The 6 in and 8 in sizes have a .044 in rim and the 10 in has .052 in. A removable bushing lets you adjust the arbor hole.', features = '["Longer lasting", "Thick rim", "Best for agates & geodes"]', included = '["Bushing (removable with flat-blade screwdriver if arbor hole adjustment is needed)"]', specs = '{"6\\"": "0.044\\" rim, 5/8\\"-1/2\\" arbor", "8\\"": "0.044\\" rim, 5/8\\"-1/2\\" arbor", "10\\"": "0.052\\" rim, 5/8\\"-1/2\\" arbor", "12\\"": "0.070\\" rim, 1\\"-5/8\\" arbor", "14\\"": "0.070\\" rim, 1\\"-5/8\\" arbor"}', warranty = NULL WHERE id = 'covington-black-sintered-diamond-saw-blades';
UPDATE products SET blurb = 'Covington Platinum Resin 5000 Diamond Saw Blades are resin-bonded blades with a very high diamond concentration and 1/4 in of diamond depth.

They make cleaner cuts than standard plated blades and suit heat-sensitive material. Diameters are 10, 12 and 14 in, with a .062 in kerf on the 10 and 12 in and .072 in on the 14 in.', features = '["1/4\\" diamond depth", "Super heavy diamond concentration", "Resin-bonded construction", "Cleaner cuts than standard plated blades", "Ideal for heat-sensitive materials"]', included = '[]', specs = '{"10\\" and 12\\" kerf": ".062\\"", "14\\" kerf": ".072\\"", "Diameters": "10\\", 12\\", 14\\"", "Arbor": "1/2\\", 5/8\\""}', warranty = NULL WHERE id = 'covington-platinum-resin-5000-diamond-saw-blades';
