-- Batch 12 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'The Inland Sintered Diamond Bur in the Inverted Cone shape is widest at the tip.

Its 3/32 in shaft is 35 mm long. Sizes are 4 x 12 mm, 6 x 13 mm and 8 x 13 mm, in 100, 220, 325 and 600 grit.', features = '["Uniform matrix of diamond crystals in durable binder", "Lasts 5-10x longer than diamond plated burs", "Lasts up to 100x longer than silicon carbide or aluminum oxide points", "3/32\\" shaft, 35mm long (excluding diamond portion)"]', included = '[]', specs = '{"Sizes": "4mm x 12mm, 6mm x 13mm, 8mm x 13mm", "Grits": "100, 220, 325, 600"}', warranty = NULL WHERE id = 'inland-sintered-diamond-bur-inverted-cone';
UPDATE products SET blurb = 'The Inland Sintered Diamond Bur in the Flat Head Inverted Cone shape combines a flat working face with a flared body.

The 3/32 in shaft is 35 mm long. Sizes are 6 x 2 mm, 8 x 3 mm and 10 x 3.5 mm, in 100, 220, 325 and 600 grit.', features = '["Uniform matrix of diamond crystals in durable binder", "Lasts 5-10x longer than diamond plated burs", "Lasts up to 100x longer than silicon carbide or aluminum oxide points", "3/32\\" shaft, 35mm long (excluding diamond portion)"]', included = '[]', specs = '{"Sizes": "6mm x 2mm, 8mm x 3mm, 10mm x 3.5mm", "Grits": "100, 220, 325, 600"}', warranty = NULL WHERE id = 'inland-sintered-diamond-bur-flat-head-inverted-cone';
UPDATE products SET blurb = 'The Inland Sintered Diamond Bur in the Flat Head Cylinder shape is a straight-sided bur with a flat end.

The 3/32 in shaft is 35 mm long. Sizes are 4 x 12 mm, 6 x 13 mm and 8 x 13 mm, in 100, 220, 325 and 600 grit.', features = '["Uniform matrix of diamond crystals in durable binder", "Lasts 5-10x longer than diamond plated burs", "Lasts up to 100x longer than silicon carbide or aluminum oxide points", "3/32\\" shaft, 35mm long (excluding diamond portion)"]', included = '[]', specs = '{"Sizes": "4mm x 12mm, 6mm x 13mm, 8mm x 13mm", "Grits": "100, 220, 325, 600"}', warranty = NULL WHERE id = 'inland-sintered-diamond-bur-flat-head-cylinder';
UPDATE products SET blurb = 'The Inland Sintered Diamond Bur in the Flat Head Cone shape tapers to a flat tip and comes in a single 4 x 10 mm size.

It is a sintered bur on a 3/32 in shaft, 35 mm long, offered in 100, 220, 325 and 600 grit.', features = '["Uniform matrix of diamond crystals in durable binder", "Lasts 5-10x longer than diamond plated burs", "Lasts up to 100x longer than silicon carbide or aluminum oxide points", "3/32\\" shaft, 35mm long (excluding diamond portion)"]', included = '[]', specs = '{"Size": "4mm x 10mm", "Grits": "100, 220, 325, 600"}', warranty = NULL WHERE id = 'inland-sintered-diamond-bur-flat-head-cone';
UPDATE products SET blurb = 'The Inland Sintered Diamond Carving Bur in the Flame shape is a pointed, curved-profile bur for detailed carving.

The shaft is 3/32 in and 35 mm long. Sizes are 5 x 12 mm and 7 x 13 mm, in 100, 220, 325 and 600 grit.', features = '["Uniform matrix of diamond crystals in durable binder", "Lasts 5-10x longer than diamond plated burs", "Lasts up to 100x longer than silicon carbide or aluminum oxide points", "3/32\\" shaft, 35mm long (excluding diamond portion)"]', included = '[]', specs = '{"Sizes": "5mm x 12mm, 7mm x 13mm", "Grits": "100, 220, 325, 600"}', warranty = NULL WHERE id = 'inland-sintered-diamond-carving-bur-flame';
UPDATE products SET blurb = 'The Inland Sintered Diamond Bur in the Drum shape is a short, wide cylinder.

The 3/32 in shaft is 35 mm long. Sizes are 6 x 2 mm, 8 x 3 mm and 10 x 3 mm, in 100, 220, 325 and 600 grit.', features = '["Uniform matrix of diamond crystals in durable binder", "Lasts 5-10x longer than diamond plated burs", "Lasts up to 100x longer than silicon carbide or aluminum oxide points", "3/32\\" shaft, 35mm long (excluding diamond portion)"]', included = '[]', specs = '{"Sizes": "6mm x 2mm, 8mm x 3mm, 10mm x 3mm", "Grits": "100, 220, 325, 600"}', warranty = NULL WHERE id = 'inland-sintered-diamond-bur-drum';
UPDATE products SET blurb = 'The Tumble-Bee 4 lb Rock Tumbler Extra Barrel is a complete rubber barrel with all its parts, made to fit any Tumble-Bee tumbler.

It measures 4 in inside diameter, 4-1/2 in outside diameter and 7-1/2 in tall.', features = '["Complete with all barrel parts", "Rubber barrel construction", "Compatible with any Tumble-Bee rock tumbler"]', included = '[]', specs = '{"Inner diameter": "4\\"", "Outer diameter": "4-1/2\\"", "Height": "7-1/2\\""}', warranty = NULL WHERE id = 'tumble-bee-4-lb-rock-tumbler-extra-barrel';
UPDATE products SET blurb = 'The Tumble-Bee 2 lb Rock Tumbler Extra Barrel is a complete rubber barrel with all its parts, made to fit any Tumble-Bee tumbler.

It measures 4 in inside diameter, 4-1/2 in outside diameter and 4 in tall.', features = '["Complete with all barrel parts", "Rubber barrel construction", "Compatible with any Tumble-Bee rock tumbler"]', included = '[]', specs = '{"Inner diameter": "4\\"", "Outer diameter": "4-1/2\\"", "Height": "4\\""}', warranty = NULL WHERE id = 'tumble-bee-2-lb-rock-tumbler-extra-barrel';
UPDATE products SET blurb = 'The Tumble-Bee 2 x 2 Rock Tumbler turns two 2 lb rubber barrels at once.

A grooved non-slip belt drives the barrels, a thermal overload protector guards the motor, moving parts are shielded and the switch is lit. The housing is rust-proof composite. It measures 13 x 6 x 6 in and weighs 6 lb, and ships with a bottle of light oil, an Allen wrench and an instruction manual.', features = '["Non-slip drive belt with grooved design", "Thermal overload protector", "Lighted on/off power switch", "Shielded moving parts", "Rust-proof composite housing"]', included = '["Two 2 lb rubber barrels", "One bottle of lightweight oil", "3/64\\" Allen wrench", "Instruction manual"]', specs = '{"Dimensions": "13\\" L x 6\\" W x 6\\" H", "Weight": "6 lb"}', warranty = NULL WHERE id = 'tumble-bee-2-x-2-rock-tumbler';
UPDATE products SET blurb = 'The Tumble-Bee 1 x 4 Rock Tumbler is a single-barrel tumbler with a 4 lb rubber barrel.

The drive belt is polyurethane with embedded polyester fibers, and the motor has a thermal overload protector. Moving parts are shielded, the power switch lights up and the housing is rust-proof composite. It measures 13 x 6 x 6 in. A bottle of light oil, an Allen wrench and an instruction manual are included.', features = '["Non-slip drive belt (polyurethane with embedded polyester fibers)", "Thermal overload protector", "Lighted on/off power switch", "Shielded moving parts", "Rust-proof composite housing"]', included = '["One 4 lb rubber barrel", "One bottle of lightweight oil", "3/64\\" Allen wrench", "Instruction manual"]', specs = '{"Dimensions": "13\\" L x 6\\" W x 6\\" H"}', warranty = NULL WHERE id = 'tumble-bee-1-x-4-rock-tumbler';
