-- Batch 16 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'The Hi-Tech Diamond Disc Bushing is a precisely machined, tight-tolerance bushing that keeps discs centered so misalignment does not cause vibration.

It fits All-U-Need and Slant Cabber machines.', features = '["Precisely machined", "High tolerance", "Prevents vibration from misalignment", "For All-U-Need and Slant Cabber machines"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'hi-tech-diamond-disc-bushing';
UPDATE products SET blurb = 'The Hi-Tech Diamond Saw Fence is an adjustable fence for lining material up accurately.

It fits the Hi-Tech Diamond 6 in trim saw and 10 in slab saw.', features = '["Precise material alignment", "Easily adjustable", "Fits Hi-Tech Diamond 6\\" trim saw and 10\\" slab saw"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'hi-tech-diamond-saw-fence';
UPDATE products SET blurb = 'Hi-Tech Diamond Electroplated Diamond Lap Discs are 1 mm steel discs in 6 in or 8 in diameter, with grits from 60 to 3000.

An optional 3M pressure-sensitive adhesive backing is available. They fit All-U-Need and Slant Cabber machines and any lap machine with a 1/2 in arbor, to a maximum of 4,000 rpm.', features = '["6\\" or 8\\" diameter", "Multiple grit options (60-3000)", "Optional 3M pressure-sensitive adhesive backing", "Compatible with All-U-Need and Slant Cabber machines", "Fits any lap machine with 1/2\\" arbor", "Max RPM 4,000"]', included = '[]', specs = '{"Steel disc thickness": "1mm", "Sizes": "6\\", 8\\"", "Arbor": "1/2\\""}', warranty = NULL WHERE id = 'hi-tech-diamond-electroplated-diamond-lap-discs';
UPDATE products SET blurb = 'The Hi-Tech Diamond 10 Inch Slab Saw has a 1/3 hp, 1,725 rpm motor and comes with two blades, one notched and one sintered.

The housing is rustproof cross-linked polyethylene, the saw table lifts out, and the coolant reservoir has a drain plug. The arbor is 5/8 in and blade height is 3-3/4 in. A spray shield, Allen wrench and instruction manual are included. It measures 19 x 21 x 12 in, weighs 35 lb, is made in the USA and carries a one-year manufacturer\'s warranty.', features = '["Two diamond blades included (notched + sintered)", "5/8\\" arbor", "1/3 hp motor, 1,725 rpm", "Removable saw table", "Cross-linked polyethylene housing, rustproof", "Coolant reservoir with drain plug", "Spray shield and Allen wrench included", "Made in the USA"]', included = '["Spray shield", "Allen wrench", "Instruction manual"]', specs = '{"Dimensions": "19\\" L x 21\\" W x 12\\" H", "Weight": "35 lb", "Blade height": "3-3/4\\"", "Blade depth": "9-3/4\\""}', warranty = '1-year manufacturer\'s warranty' WHERE id = 'hi-tech-diamond-10-inch-slab-saw';
UPDATE products SET blurb = 'The Hi-Tech Diamond 6 Inch Trim Saw runs on a 1/4 hp variable-speed motor from 800 to 3,400 rpm.

Sealed ball bearings support the 5/8 in arbor, the 16 oz coolant reservoir holds coolant, and the saw table can be removed. It ships with two diamond blades, a spray shield, an Allen wrench and an instruction manual. It is made in the USA with a one-year manufacturer\'s warranty.', features = '["Two diamond blades included", "1/4 hp variable speed motor, 800-3,400 rpm", "Sealed ball bearings", "5/8\\" arbor", "16 oz coolant reservoir", "Removable saw table", "Made in the USA"]', included = '["Two diamond saw blades", "Spray shield", "Allen wrench", "Instruction manual"]', specs = '{}', warranty = '1-year manufacturer\'s warranty' WHERE id = 'hi-tech-diamond-6-inch-trim-saw';
UPDATE products SET blurb = 'The Hi-Tech Diamond 4 and 5 Inch Trim Saw comes with both a 4 in and a 5 in diamond blade, and drives them with a 1/4 hp variable-speed motor from 800 to 3,400 rpm.

The arbor is 5/8 in, the bearings are sealed, and the 7-1/2 x 4-3/4 in saw table is removable. It measures 13 x 9-1/2 x 7 in and weighs 10 lb. A spray shield, Allen wrench and manual are supplied. Made in the USA, one-year manufacturer\'s warranty.', features = '["4\\" and 5\\" diamond saw blades included", "5/8\\" arbor", "1/4 hp variable speed motor, 800-3,400 rpm", "Sealed ball bearings", "Removable saw table", "Made in the USA"]', included = '["Spray shield", "Allen wrench", "Instruction manual"]', specs = '{"Dimensions": "13\\" L x 9-1/2\\" W x 7\\" H", "Weight": "10 lb", "Saw table": "7-1/2\\" L x 4-3/4\\" W"}', warranty = '1-year manufacturer\'s warranty' WHERE id = 'hi-tech-diamond-4-and-5-inch-trim-saw';
UPDATE products SET blurb = 'The Hi-Tech Diamond Slant Cabber, Glass & Crystal Model, is a tilted-bed lap machine with a 1/4 hp variable-speed motor running 800 to 3,400 rpm.

The housing is rustproof polyethylene, and the water reservoir has a control valve and a splash guard. The starter set includes 360, 600, 1,200 and 3,000 grit electroplated diamond discs, a Tech-11 polishing pad and a 2-gram syringe of 14,000 grit diamond compound. It measures 13-1/2 x 15 x 11 in, weighs 12 lb, is made in the USA and has a one-year warranty.', features = '["1/4 hp variable speed motor, 800-3,400 rpm", "Quiet running", "Rustproof polyethylene housing", "Water reservoir with control valve", "Splash guard", "Made in the USA"]', included = '["360, 600, 1,200, and 3,000 grit electroplated diamond discs", "Tech-11 polishing pad", "2-gram 14,000 grit diamond paste syringe", "Two acrylic backing plates", "Two disc bushings", "Allen wrench", "Instruction manual"]', specs = '{"Dimensions": "13-1/2\\" L x 15\\" W x 11\\" H", "Weight": "12 lb"}', warranty = '1-year manufacturer\'s warranty' WHERE id = 'hi-tech-diamond-slant-cabber-glass-crystal-model';
UPDATE products SET blurb = 'The Hi-Tech Diamond Slant Cabber, Rock & Mineral Model, has an angled design that lets you work seated, driven by a 1/4 hp variable-speed motor from 800 to 3,400 rpm.

The housing is rustproof polyethylene. The accessory kit starts with a 180 grit electroplated diamond lap and diamond smoothing discs beginning at 325 grit. It measures 13-1/2 x 15 x 11 in, weighs 12 lb and carries a one-year manufacturer\'s warranty.', features = '["1/4 hp variable speed motor, 800-3,400 rpm", "Rustproof polyethylene housing", "Angled design for seated operation", "Accessory kit included"]', included = '["180 grit electroplated diamond lap", "325 grit brown diamond smoothing disc", "600 grit red diamond smoothing disc", "1,200 grit blue diamond smoothing disc", "Tech-11 polishing pad", "2-gram 14,000 grit diamond paste syringe", "4 acrylic backing plates", "Allen wrench", "Instruction manual"]', specs = '{"Dimensions": "13-1/2\\" L x 15\\" W x 11\\" H", "Weight": "12 lb"}', warranty = '1-year manufacturer\'s warranty' WHERE id = 'hi-tech-diamond-slant-cabber-rock-mineral-model';
UPDATE products SET blurb = 'The Hi-Tech Diamond All-U-Need Flat Lap Machine, Glass & Crystal Model, is a light, portable flat lap with a 1/4 hp variable-speed motor from 800 to 3,400 rpm.

It has an impact-resistant, rustproof ABS housing, a coolant reservoir and a splash guard. The kit includes 360, 600, 1,200 and 3,000 grit electroplated diamond discs, a Tech-11 polishing pad and a 2-gram syringe of 14,000 grit diamond compound. It is 10 x 10 x 12 in, weighs 9 lb, is made in the USA and has a one-year warranty.', features = '["1/4 hp variable speed motor, 800-3,400 rpm", "Lightweight and portable", "Impact resistant, rustproof ABS housing", "Coolant reservoir and splash guard", "Made in the USA"]', included = '["360, 600, 1,200, and 3,000 grit electroplated diamond discs", "Tech-11 polishing pad", "2-gram 14,000 grit diamond paste syringe", "2 acrylic backing plates", "2 disc bushings", "Water kit", "Allen wrench", "Instruction manual"]', specs = '{"Dimensions": "10\\" L x 10\\" W x 12\\" H", "Weight": "9 lb"}', warranty = '1-year manufacturer\'s warranty' WHERE id = 'hi-tech-diamond-all-u-need-flat-lap-machine-glass-crystal-model';
UPDATE products SET blurb = 'The Hi-Tech Diamond All-U-Need Flat Lap Machine, Rock & Mineral Model, is a light, quiet flat lap with a 1/4 hp variable-speed motor running 800 to 3,400 rpm.

The rustproof ABS housing includes a splash guard, and a water kit and coolant reservoir are supplied. The disc set has a 180 grit electroplated diamond lap plus 325, 600 and 1,200 grit diamond smoothing discs and a Tech-11 pad. It is 10 x 10 x 12 in, weighs 9 lb, is made in the USA and carries a one-year warranty.', features = '["1/4 hp variable speed motor, 800-3,400 rpm", "Quiet operation", "Water kit and coolant reservoir included", "Splash guard", "Lightweight rustproof ABS housing", "Made in the USA"]', included = '["180 grit electroplated diamond lap", "325, 600, and 1,200 grit diamond smoothing discs", "Tech-11 polishing pad", "2-gram 14,000 grit diamond paste syringe", "4 acrylic backing plates", "Allen wrench", "Instruction manual"]', specs = '{"Dimensions": "10\\" L x 10\\" W x 12\\" H", "Weight": "9 lb"}', warranty = '1-year manufacturer\'s warranty' WHERE id = 'hi-tech-diamond-all-u-need-flat-lap-machine-rock-mineral-model';
