-- Batch 7 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'Covington C-Series Signature Saw Blades have a textured rim that helps wash sediment out of the cut.

Diameters run from 6 in to 20 in with arbor sizes of 1/2, 5/8, 3/4 and 1 in. Kerf is .040 in on the 6 to 10 in blades, .060 in on 12 to 16 in and .085 in on 18 to 20 in. Covington positions them as a step up from MK\'s 301 blade.', features = '["Textured rim for better sediment washout", "6\\" to 20\\" diameters", "Kerf: .040 (6\\"-10\\"), .060 (12\\"-16\\"), .085 (18\\"-20\\")", "Better than MK\'s 301 blades"]', included = '[]', specs = '{"Diameters": "6\\", 8\\", 10\\", 12\\", 14\\", 16\\", 18\\", 20\\"", "Arbor sizes": "1/2\\", 5/8\\", 3/4\\", 1\\""}', warranty = NULL WHERE id = 'covington-c-series-signature-saw-blades';
UPDATE products SET blurb = 'Rockhounding Oregon by Lars W. Johnson is a collecting guide to sites across the state, including Little Glass Butte, Richardson\'s Rock Ranch and Graveyard Point.

Each site comes with GPS coordinates, a map, color photographs and notes on driving conditions.', features = '["Covers Little Glass Butte, Richardson\'s Rock Ranch, Graveyard Point", "GPS coordinates", "Maps", "Color photos", "Driving conditions info"]', included = '[]', specs = '{"Author": "Lars W. Johnson"}', warranty = NULL WHERE id = 'rockhounding-oregon';
UPDATE products SET blurb = 'Gem Trails of Idaho & Western Montana by Lanny Ream lists 99 collecting locations across the two regions.

Entries include GPS coordinates, maps, photographs, road conditions and advice on the tools to bring to each site.', features = '["99 collecting locations", "GPS coordinates", "Tool guidance per site", "Road conditions information", "Maps and photos"]', included = '[]', specs = '{"Author": "Lanny Ream"}', warranty = NULL WHERE id = 'gem-trails-of-idaho-western-montana';
UPDATE products SET blurb = 'Covington A-Series Signature Saw Blades are general-purpose diamond blades that Covington compares to MK Diamond\'s 303.

Blades of 6 to 14 in have a continuous rim; 16 in and larger are segmented. Sizes span 4 to 24 in with arbor sizes of 1/2 to 1 in and widths from .014 to .100 in. One is included with Covington saws of 12 in and up.', features = '["Comparable to MK Diamond\'s 303", "6\\"-14\\" continuous rim", "16\\"+ segmented rim", "Included with Covington 12\\"+ saws"]', included = '[]', specs = '{"Diameters": "4\\"-24\\"", "Arbor sizes": "1/2\\"-1\\"", "Widths": ".014\\"-.100\\""}', warranty = NULL WHERE id = 'covington-a-series-signature-saw-blades';
UPDATE products SET blurb = 'The Crystalite Channel Disc has a surface of randomly spaced diamond islands that cuts fast and coarse.

It is well suited to roughing out facets and grinding the backs of cabochons. The arbor hole is 1/2 in. Available as 6 in/1200 grit or 8 in in 180, 260, 360 and 1200 grit.', features = '["Randomly interspaced island surface", "Fast, coarse cutting", "Good for rough facet cutting and cabochon back grinding"]', included = '[]', specs = '{"Arbor hole": "1/2\\"", "Sizes/grits": "6\\"/1200, 8\\"/180, 8\\"/260, 8\\"/360, 8\\"/1200"}', warranty = NULL WHERE id = 'crystalite-channel-disc';
UPDATE products SET blurb = 'Covington 6 Inch Radius Wheels are electroplated diamond wheels with a curved edge profile, made for shaping rounded surfaces.

Choose a 1/2 in or 1 in width in 80, 100, 220, 360 or 600 grit.', features = '["Curved surface", "Electroplated", "High quality", "Economical", "Available in 1\\" & 1/2\\" widths"]', included = '[]', specs = '{"Widths": "1/2\\", 1\\"", "Grits": "80, 100, 220, 360, 600"}', warranty = NULL WHERE id = 'covington-6-inch-radius-wheels';
UPDATE products SET blurb = 'The Covington Glass Engraver is a 1/2 hp bench machine for engraving glass and cutting it with wheels up to 6 in across.

Speed adjusts up to 1600 rpm, the wheels are open on all sides for unobstructed access, and an adjustable waterspout, 1/2 gallon drip can and two waste pans manage the water. It has a 1/4 in Jacob\'s chuck with wheel adapter, sealed ball bearings greased for life, a belt guard and a flexible lamp. Five 320 grit aluminum oxide engraving wheels and a thin-flex diamond cutting blade are supplied.', features = '["Unobstructed access to wheels", "1/2 gallon drip can", "2 water waste pans", "Adjustable waterspout", "Adjustable speed up to 1600 rpm", "1/4\\" Jacob\'s chuck and wheel adapter", "Heavy duty sealed ball bearings, greased for life", "1/2 hp motor", "Belt guard", "Flexible lamp"]', included = '["5 assorted mandrel-mounted 320 grit aluminum oxide engraving wheels", "1 thin-flex diamond cutting blade", "Instructions"]', specs = '{"Motor": "1/2 hp", "Max speed": "1600 rpm"}', warranty = 'Manufacturer\'s warranty included' WHERE id = 'covington-glass-engraver';
UPDATE products SET blurb = 'The Inland Craft GrinderStation is a four-panel folding vinyl shield that contains overspray from your grinder.

Opened out it is 25 in wide and 12 in high, it wipes clean, and it has a cutout for the power cord.', features = '["Contains overspray during grinding", "4 foldable panels, 25\\" wide x 12\\" high open", "Washable vinyl construction", "Cutout hole for power cord"]', included = '[]', specs = '{"Dimensions open": "25\\" W x 12\\" H", "Material": "Vinyl"}', warranty = NULL WHERE id = 'inland-craft-grinderstation';
UPDATE products SET blurb = 'The CabKing Felt Polishing Pad is a 6 in round pad of high-density natural wool felt, 1/8 in thick.

It has a 3M adhesive backing for mounting on a wheel or plate.', features = '["High quality", "Durable", "High density", "All natural wool felt", "1/8\\" thick", "6\\" diameter", "3M adhesive backing"]', included = '[]', specs = '{"Diameter": "6\\"", "Thickness": "1/8\\""}', warranty = NULL WHERE id = 'cabking-felt-polishing-pad';
UPDATE products SET blurb = 'Covington 10 Inch Diamond Discs for Perfect Maxi Lap are nickel-bond, magnetic-backed discs in eight grits: 60, 80, 100, 140, 200, 270, 325 and 500.', features = '["Nickel bond", "Magnetic backed", "Variety of grits"]', included = '[]', specs = '{"Size": "10\\"", "Grits available": "60, 80, 100, 140, 200, 270, 325, 500"}', warranty = NULL WHERE id = 'covington-10-inch-diamond-discs-for-perfect-maxi-lap';
