-- Batch 39 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'The Covington 3-Headed Sphere Machine makes spheres from 2-1/2 in to 10 in with three 1/6 hp gear motors, each mounted on its own swivel base.

Each motor turns at 161 rpm with 60 in-lb of torque. The frame is heavy steel, 36 in tall, with a water tower and automatic grit feed. It ships with a grit catch pan, one set of three cutter cups, instructions and the product guarantee, and weighs 255 lb.', features = '["Three 1/6 hp, heavy duty gear motors", "110V, 60Hz", "161 rpm with 60 in-lb of torque", "Each motor independently mounted on a swivel base", "Stands 36\\" high with water tower and grit feed", "Automatic grit application", "Heavy steel frame and guides", "Powder coated for durability and rust resistance", "Made in USA"]', included = '["One grit catch pan", "Instructions", "Product guarantee", "One set of three cutter cups (size specified by customer)"]', specs = '{"Weight": "255 lb", "Sphere sizes": "2-1/2\\" to 10\\""}', warranty = 'Product guarantee included' WHERE id = 'covington-3-headed-sphere-machine';
UPDATE products SET blurb = 'The Crystalite Lap Disk Protector Storage Container holds a single 6 in or 8 in lap disk in a stackable high-impact polystyrene case with interlocking grooves.

Choose the arbor hole or screwback mounting style.', features = '["Holds single 6\\" or 8\\" lap disk", "High impact polystyrene construction", "Stackable design with interlocking grooves", "Available in arbor hole or screwback mounting styles"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'crystalite-lap-disk-protector-storage-container';
UPDATE products SET blurb = 'The Covington Single Quart Rolling Rock Tumbler is a small American-made tumbler that handles a 3 lb load in a solid LLDPE barrel.

A fan-cooled motor drives it on DuPont nylon bearings and steel support shafts, in a cast aluminum chassis with a powder-coated frame and belt guard. Instructions and the manufacturer\'s warranty are included.', features = '["Solid LLDPE barrel", "Cast aluminum chassis", "Powder coated frame and belt guard", "Steel support shafts", "DuPont nylon bearings", "Fan cooled motor", "3 lb total capacity", "Instructions included", "Made in the USA"]', included = '["Instructions"]', specs = '{"Barrel capacity": "3 lb of rocks"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-single-quart-rolling-rock-tumbler';
UPDATE products SET blurb = 'The Rock Tumbler Starter Grit and Polish Kit is a small-batch starter set for one tumbler run.

It holds 1 lb of 60/90 coarse grit, 12 oz of 120/220 medium grit, 12 oz of 3F/400 fine grit and 12 oz of Gold Polish. Larger 1 lb and 5 lb kits are also available.', features = '["Complete starter set for a small tumbler run", "Also available in 1 lb and 5 lb kit sizes"]', included = '["1 lb 60/90 coarse grit", "12 oz 120/220 medium grit", "12 oz 3F/400 fine grit", "12 oz Gold Polish #1", "6 oz Old Miser binding agent"]', specs = '{}', warranty = NULL WHERE id = 'rock-tumbler-starter-grit-and-polish-kit';
UPDATE products SET blurb = 'Covington Pinewood Dop Sticks come as ten 4 in sticks: two each of 3/16, 1/4, 5/16, 3/8 and 1/2 in diameters.', features = '["Ten 4-inch hardwood dop sticks", "Two sticks each in five diameters"]', included = '["Ten 4\\" pinewood dop sticks (2 each of 3/16\\", 1/4\\", 5/16\\", 3/8\\", 1/2\\")"]', specs = '{"Length": "4\\"", "Diameters": "3/16\\", 1/4\\", 5/16\\", 3/8\\", 1/2\\""}', warranty = NULL WHERE id = 'covington-pinewood-dop-sticks';
UPDATE products SET blurb = 'Covington Green Dop Wax is a standard-formula dop wax that bonds strongly and softens at 150°F for easy removal.

Sold as a 1 lb package.', features = '["Industry-standard formulation", "Strong bonding capability", "Softens at 150\\u00b0F for easy removal"]', included = '[]', specs = '{"Weight": "1 lb", "Softening temperature": "150\\u00b0F"}', warranty = NULL WHERE id = 'covington-green-dop-wax-1-pound';
UPDATE products SET blurb = 'Covington Black Dop Wax is an extra-strong, high-temperature dop wax that softens at 170°F.

Sold as a 1 lb package.', features = '["Extra strong", "High temperature", "Softens at 170\\u00b0F"]', included = '[]', specs = '{"Weight": "1 lb", "Softening temperature": "170\\u00b0F"}', warranty = NULL WHERE id = 'covington-black-dop-wax-1-pound';
UPDATE products SET blurb = 'The Covington 36 Inch Rociprolap Flat Lap Machine is the largest Rociprolap, with a 1/2 hp motor and the capacity to lap pieces up to 275 lb.

It reciprocates 575 times a minute on a heavy cast iron base and lap plate with sealed ball bearings. A splash guard, bumper ring, motor and a set of twelve 5/8 in nylon ball bearings are included. It weighs 300 lb and is made in the USA, with a one-year guarantee from the date of purchase.', features = '["Heavy duty sealed ball bearings", "Heavy cast iron base and lap plate", "Heavy duty 1/2 hp motor", "Splash guard", "Largest Rociprolap model", "Holds up to 275 lb", "Made in USA"]', included = '["Splash guard", "Bumper ring", "Motor", "One set of twelve 5/8\\" nylon ball bearings", "One set of 6 steel discs", "Polish pad", "Instructions"]', specs = '{"Weight": "300 lb", "Reciprocation rate": "575 times per minute", "Capacity": "up to 275 lb"}', warranty = 'Covington Engineering guarantees the machines for one year from the date of purchase against any defects (excludes nylon thrust bearings, steel discs and leveling feet).' WHERE id = 'covington-36-inch-rociprolap-flat-lap-machine';
UPDATE products SET blurb = 'The Covington 30 Inch Rociprolap Flat Lap Machine has a 1/2 hp motor and can lap pieces up to 225 lb.

It sits on a heavy cast iron base and lap plate with sealed ball bearings. A splash guard, bumper ring, motor and a set of twelve 5/8 in nylon ball bearings come with it. It weighs 275 lb, is made in the USA and has a one-year guarantee from the date of purchase.', features = '["Heavy duty sealed ball bearings", "Heavy cast iron base and lap plate", "Heavy duty 1/2 hp motor", "Splash guard included", "Laps up to 225 lb", "Made in USA"]', included = '["Splash guard", "Bumper ring", "Motor", "One set of twelve 5/8\\" nylon ball bearings", "One set of 6 steel discs", "Polish pad", "Instructions"]', specs = '{"Weight": "275 lb", "Capacity": "up to 225 lb"}', warranty = 'Covington Engineering guarantees the machines for one year from the date of purchase against any defects (excludes nylon thrust bearings, steel discs and leveling feet).' WHERE id = 'covington-30-inch-rociprolap-flat-lap-machine';
UPDATE products SET blurb = 'The Covington 24 Inch Rociprolap Flat Lap Machine is the most popular Rociprolap size, holding up to 175 lb.

A 1/2 hp motor drives it on a heavy cast iron base and lap plate with sealed ball bearings. The package includes twelve 5/8 in nylon ball bearings, six steel discs, a polish pad and a splash guard. It weighs 280 lb, is made in the USA and has a one-year guarantee from the date of purchase.', features = '["Heavy duty sealed ball bearings", "Heavy cast iron base and lap plate", "Heavy duty 1/2 hp motor", "Splash guard included", "Most popular size", "Holds up to 175 lb capacity", "Made in USA"]', included = '["One set of twelve 5/8\\" nylon ball bearings", "One set of 6 steel discs", "Polish pad", "Splash guard", "Bumper ring", "Motor", "Instructions"]', specs = '{"Weight": "280 lb"}', warranty = 'Covington Engineering guarantees the machines for one year from the date of purchase against any defects (excludes nylon thrust bearings, steel discs and leveling feet).' WHERE id = 'covington-24-inch-rociprolap-flat-lap-machine';
