-- Batch 35 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'Covington Platinum 303 Diamond Saw Blades cut smoothly and keep waste low on rare or valuable material.

They last longer and cut faster than notched-rim or plated blades. Blades of 16 in and larger are segmented rim. Sizes start at 4 in and 5 in with a .020 core, and the 6 in has a .032 core.', features = '["Smooth cuts", "Minimizes waste on rare or valuable materials", "Lasts longer and cuts faster than notched rim or plated blades", "16\\" and larger are segmented rim blades"]', included = '[]', specs = '{"4\\"": "0.020 core, 5/8\\"-1/2\\" arbor", "5\\"": "0.020 core, 5/8\\"-1/2\\" arbor", "6\\"": "0.032 core, 5/8\\"-1/2\\" arbor", "8\\"": "0.025 core, 5/8\\"-1/2\\" arbor", "10\\"": "0.032 core, 5/8\\"-1/2\\" arbor", "12\\"": "0.065 core, 1\\"-5/8\\" arbor", "14\\"": "0.065 core, 1\\"-5/8\\" arbor", "16\\" (segmented)": "0.085 core, 1\\"-5/8\\" arbor", "18\\" (segmented)": "0.085 core, 1\\"-3/4\\" arbor", "20\\" (segmented)": "0.100 core, 1\\"-3/4\\" arbor", "24\\" (segmented)": "0.100 core, 1\\" arbor", "30\\" (segmented)": "0.125 core, 1\\" arbor", "36\\" (segmented)": "0.200 core, 1\\" arbor"}', warranty = NULL WHERE id = 'covington-platinum-303-diamond-saw-blades';
UPDATE products SET blurb = 'Covington Rock Tumblers Replacement Barrels are solid LLDPE barrels supplied with a lid and clamp.

Sizes are quart (3 lb), 1/2 gallon (6 lb) and gallon (12 lb).', features = '["Solid LLDPE barrel", "Comes with lid and clamp", "Quart barrel weight capacity 3 lb", "1/2 gallon barrel weight capacity 6 lb", "Gallon barrel weight capacity 12 lb"]', included = '["Lid and clamp"]', specs = '{"Sizes": "Quart (3 lb), 1/2 Gallon (6 lb), Gallon (12 lb)"}', warranty = NULL WHERE id = 'covington-rock-tumblers-replacement-barrels';
UPDATE products SET blurb = 'The Covington Deluxe Rock Tumbler uses a three-way tumbling action in a solid polyvinyl barrel with easy access for checking progress.

A fan-cooled 1/21 hp motor drives it on DuPont nylon bearings in a powder-coated cast aluminum chassis. The barrel opening is 3-1/4 in and the barrel is 8 in wide and 8-1/2 in deep. A sample of Old Miser and instructions are included, with the manufacturer\'s warranty.', features = '["Unique 3-way tumbling action", "Solid polyvinyl barrel", "Easy access for checking progress", "Powder coated cast aluminum chassis", "DuPont nylon bearings", "Fan cooled 1/21 hp motor", "Sample of Old Miser included", "Instructions included"]', included = '["Sample of Old Miser", "Instructions"]', specs = '{"Barrel opening": "3-1/4\\"", "Barrel width": "8\\"", "Barrel depth": "8-1/2\\"", "Barrel capacity": "4 lb rocks / 9 lb water weight / up to 20 lb steel shot"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-deluxe-rock-tumbler';
