-- Batch 38 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'The Covington 18 Inch Flat Lap Beveler and Grinder has a heavy welded steel chassis, a 1 in stainless steel shaft with welded flange and heavy-duty ball bearings.

The shaft accepts 5/8-11 RH male accessories, an aluminum manifold controls water, and a stainless steel splash guard and brush are included. It measures 32 x 48 x 34 in and weighs 355 lb.', features = '["Aluminum water manifold controls fluid flow", "Heavy welded steel chassis", "Stainless steel splash guard and brush", "Shaft accepts 5/8\\"-11RH male accessories", "1\\" stainless steel shaft with welded flange", "Heavy-duty ball bearings", "Available in Single Speed & Variable Speed options", "Water feeds through shaft center and dual overhead loc-line"]', included = '[]', specs = '{"Weight": "355 lb", "Width": "32\\"", "Height": "34\\"", "Depth": "48\\""}', warranty = NULL WHERE id = 'covington-18-inch-flat-lap-beveler-and-grinder';
UPDATE products SET blurb = 'The Covington Rociprolap Synthetic Felt Polishing Disc for Glass is a magnetic-backed synthetic felt disc used with cerium oxide.

Sizes match the machine: 19 in for the 20 in Rociprolap, 22 in for the 24 in, 28 in for the 30 in and 35 in for the 36 in.', features = '["Magnetic backing", "Synthetic felt material", "Compatible with Rociprolap machines", "Works with cerium oxide polish compound"]', included = '[]', specs = '{"Sizes": "19\\" (20\\" Rociprolap), 22\\" (24\\" Rociprolap), 28\\" (30\\" Rociprolap), 35\\" (36\\" Rociprolap)"}', warranty = NULL WHERE id = 'covington-rociprolap-synthetic-felt-polishing-disc-for-glass';
UPDATE products SET blurb = 'Splash Guards for Covington Rociprolap Flat Lap Machines are reusable, easy-to-clean guards made of fiber-reinforced plastic.

Sizes are 20, 24, 30 and 36 in.', features = '["High quality", "Fiber-reinforced plastic", "Easy to clean", "Reusable"]', included = '[]', specs = '{"Sizes": "20\\", 24\\", 30\\", 36\\""}', warranty = NULL WHERE id = 'splash-guards-for-covington-rociprolap-flat-lap-machines';
UPDATE products SET blurb = 'Extra Pans for Covington Rociprolap Lap Machines are spare or replacement pans machined perfectly flat to very tight tolerances.

Sizes are 20, 24, 30 and 36 in.', features = '["Machined perfectly flat", "Extremely tight tolerances", "For use as replacement or spare"]', included = '[]', specs = '{"Sizes": "20\\", 24\\", 30\\", 36\\""}', warranty = NULL WHERE id = 'extra-pans-for-covington-rociprolap-lap-machines';
UPDATE products SET blurb = 'Extra Pans for Covington Automatic Vibrating Laps are replacement pans for Vibra Lap machines in 10, 12 and 16 in sizes.

Each is size-specific and not interchangeable between base sizes.', features = '["Replacement pan for Covington Vibra Lap machines", "Size-specific, not interchangeable between base sizes"]', included = '[]', specs = '{"Sizes": "10\\", 12\\", 16\\""}', warranty = NULL WHERE id = 'extra-pans-for-covington-automatic-vibrating-laps';
UPDATE products SET blurb = 'The Revolution XT Ring Saw Aft Keel is a replacement part for the Gemini Revolution XT Ring Saw.', features = '["Replacement part for Gemini Revolution XT Ring Saw"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'revolution-xt-ring-saw-aft-keel-replacement-part';
UPDATE products SET blurb = 'The Gemini Revolution XT Complete Wear Parts Replacement Kit gathers the parts of the Revolution XT that wear most often into one order.', features = '["Covers commonly worn parts on the Gemini Revolution XT"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'gemini-revolution-xt-complete-wear-parts-replacement-kit';
UPDATE products SET blurb = 'The Gemini Revolution XT Replacement Drive Belt is an original-equipment replacement belt for the Gemini Revolution XT.', features = '["Original equipment replacement", "Fits Gemini Revolution XT"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'gemini-revolution-xt-replacement-drive-belt';
UPDATE products SET blurb = 'Gemini Revolution XT Saw Blades are 10 in sintered diamond blades with diamond on both the front and back, so the saw can cut forward and backward.

One universal blade makes straight or curved cuts, and its stiff, stable operation makes it easy to slice a piece off the edge of a workpiece.', features = '["Able to make straight or curve cuts", "Easily cuts a slice off the edge of material with stable, rigid blade operation", "Diamond coating on front and back for forward and backward cutting", "Universal blade, no need to change blades for different materials", "Material will never glaze over, no blade dressing required", "10 inch diameter", "Sintered diamond construction"]', included = '[]', specs = '{"Diameter": "10\\"", "Coating": "Sintered diamond"}', warranty = NULL WHERE id = 'gemini-revolution-xt-saw-blades';
UPDATE products SET blurb = 'Covington Koolerant #1 is a non-flammable general-purpose blade coolant for rocks up to 6 on the Mohs scale.

Dilute 9 parts water to 1 part concentrate. Sold in quart, gallon and 5 gallon sizes.', features = '["General purpose blade coolant", "Non-flammable", "For rocks up to 6 on the Mohs scale", "Dilutes 9 parts water to 1 part concentrate"]', included = '[]', specs = '{"Sizes": "Quart, Gallon, 5-Gallon"}', warranty = NULL WHERE id = 'covington-koolerant-1-general-purpose-blade-coolant';
