-- Batch 10 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'The Gemstone Drill Head Assembly for Water Feed (Belgium Style) is a quick-connect drill head for sintered diamond core drill bits.

It requires a submersible pump system to supply the water.', features = '["Belgium style design", "Quick connect attachment", "For sintered diamond core drill bits", "Requires submersible pump system"]', included = '["Drill head assembly with quick connect"]', specs = '{}', warranty = NULL WHERE id = 'gemstone-drill-head-assembly-for-water-feed-belgium-style';
UPDATE products SET blurb = 'Covington Maxi Lap Aluminum Heads are solid billet 6061 aircraft aluminum heads in 8 in and 10 in sizes, threaded 1/2-20 right-hand.

A sponge rubber surface is available as an option.', features = '["Solid billet 6061 aircraft aluminum", "Optional sponge rubber surface", "1/2\\"-20 thread"]', included = '[]', specs = '{"Thread": "1/2\\"-20 RH", "Sizes": "8\\", 10\\""}', warranty = NULL WHERE id = 'covington-maxi-lap-aluminum-heads';
UPDATE products SET blurb = 'The Hi-Tech Diamond 6 Inch Trim Saw Vise is a precision vise made only for the Hi-Tech Diamond 6 in trim saw.

It bolts on easily and keeps your hands clear of the blade.', features = '["Easy installation", "Precision construction", "Keeps hands away from blade", "Designed exclusively for Hi-Tech Diamond 6\\" Trim Saw"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'hi-tech-diamond-6-inch-trim-saw-vise';
UPDATE products SET blurb = 'The Covington Vibrating Lap Replacement Motor is a 1/12 hp, 1550 rpm, 110V/60Hz motor with four mounting studs.

A switch cord and mounting plate come with it.', features = '["1/12 hp", "4 mounting studs", "1550 rpm", "110v, 60hz"]', included = '["Switch cord", "Mounting plate"]', specs = '{"Horsepower": "1/12 hp", "Speed": "1550 rpm", "Voltage": "110v, 60hz"}', warranty = NULL WHERE id = 'covington-vibrating-lap-replacement-motor';
UPDATE products SET blurb = 'CabKing Full Face Diamond Laps are 6 in nickel-electroplated diamond laps on a 1 mm steel plate, with no center hole.

Grits range from 60 to 3000, and the back has a 1/4-20 thread.', features = '["Nickel electroplated", "1mm thick steel plate", "No center hole, full face diamond", "Grits from 60 to 3000", "1/4\\"-20 thread on back"]', included = '[]', specs = '{"Diameter": "6\\"", "Steel plate thickness": "1mm", "Thread": "1/4\\"-20"}', warranty = NULL WHERE id = 'cabking-full-face-diamond-laps';
UPDATE products SET blurb = 'The CabKing Sintered Diamond Saw Blade is an 8 in blade, .031 in thick, with a 1 in arbor hole and 325/400 diamond grit.', features = '["Sintered construction", "Premium diamond grit (325/400)", "8\\" diameter", ".031\\" thick", "1\\" arbor hole"]', included = '[]', specs = '{"Diameter": "8\\"", "Thickness": ".031\\"", "Arbor hole": "1\\""}', warranty = NULL WHERE id = 'cabking-sintered-diamond-saw-blade';
UPDATE products SET blurb = 'The Inland Wizard IV Glass Grinder has a 1/9 hp motor producing 40 oz-in of torque.

It comes with a 10 x 8-3/4 in acrylic face shield, the SecondStory work surface, two diamond grinding heads with Allen wrenches, two coolant sponges and a grinder bit splash guard. The machine measures 16 x 12.5 x 8 in and is covered by a five-year warranty.', features = '["Powerful 40 oz-in torque, 1/9 hp motor", "10\\" x 8-3/4\\" acrylic FaceShield included", "SecondStory work surface included", "Two diamond grinding heads with Allen wrenches", "Two coolant sponges", "Grinder bit splash guard", "Rustproof, impact resistant ABS housing", "Built-in storage compartment", "5-year warranty"]', included = '["1\\" diameter, 100 grit diamond grinding head with Allen wrench", "1/4\\" diameter, 100 grit diamond grinding head with Allen wrench", "Two coolant sponges", "1\\" standard BitSert", "Instruction manual"]', specs = '{"Motor": "1/9 hp, 40 oz-in torque", "Machine dimensions": "16\\" L x 12.5\\" W x 8\\" H", "Weight": "9.5 lb", "Work surface": "14-1/2\\" x 11-1/2\\""}', warranty = '5-year warranty' WHERE id = 'inland-wizard-iv-glass-grinder';
UPDATE products SET blurb = 'The Inland Diamond Grinding Head Jewelry Bit is a 1 in diameter steel head with a 5/16 in arbor fit, checked for trueness before use.

Choose a 1 mm or 1.4 mm rim in 100, 220, 360 or 600 grit. A set-screw, Allen wrench and square sponge come with it.', features = '["Measured for trueness", "5/16\\" arbor fit", "1mm or 1.4mm rim thickness", "Grit options: 100, 220, 360, 600"]', included = '["Set-screw", "Allen wrench", "Square-shaped sponge"]', specs = '{"Outer diameter": "1\\"", "Inner diameter": "5/16\\"", "Material": "Steel"}', warranty = NULL WHERE id = 'inland-diamond-grinding-head-jewelry-bit';
UPDATE products SET blurb = 'The Inland 1/4 Inch Diamond Grinding Head is used for drilling holes, grinding and shaping, and can be stacked on the larger 3/4 in or 1 in heads.

It is built on a brass core made on Swiss precision machinery and checked for trueness (TIR under .0025 in) before the diamond is applied. It fits a 0.312 in arbor, and the diamond coating is guaranteed not to peel.', features = '["For drilling holes, grinding and shaping", "Can be stacked on larger 3/4\\" or 1\\" grinding heads", "Extended diamond lifespan", "Brass cores on Swiss precision machinery", "Measured for trueness before diamond application", "Wet grinding of stone, glass, tile, minerals; dry work on plastics and woods", "Compatible with American, German, and some Chinese glass grinders"]', included = '[]', specs = '{"Arbor fit": "0.312\\" (7.92mm)", "TIR": "<.0025\\"", "Material": "CDA 360 brass cores", "Diamond surface height": "0.5\\"", "Also known as": "WB-8"}', warranty = 'Diamond coating guaranteed never to peel, free replacement for the life of the diamonds' WHERE id = 'inland-1-4-inch-diamond-grinding-head';
UPDATE products SET blurb = 'The Inland 1 Inch Diamond Grinding Head has a larger diameter for faster grinding and more usable diamond.

The brass core is machined on Swiss precision equipment and checked for trueness (TIR under .0025 in). It fits a 0.312 in arbor and is used wet on stone, glass, tile and minerals or dry on plastics. The diamond coating is guaranteed never to peel.', features = '["More usable diamond, longer lasting", "Larger diameter for faster grinding and more surface", "Brass cores on Swiss precision machinery", "Measured for trueness before diamond application", "Wet for stone, glass, tile, minerals; dry for plastics and woods", "Compatible with American, German, and some Chinese glass grinders"]', included = '[]', specs = '{"Arbor fit": "0.312\\" (7.92mm)", "TIR": "<.0025\\"", "Material": "CDA 360 brass cores", "Diamond surface height": "0.625\\"", "Also known as": "WB-9"}', warranty = 'Diamond coating guaranteed never to peel, free replacement for the life of the diamonds' WHERE id = 'inland-1-inch-diamond-grinding-head';
