-- Batch 40 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'The Covington 20 Inch Rociprolap Flat Lap Machine is the most compact Rociprolap, holding up to 125 lb on a 20 in lap plate.

A 1/2 hp motor drives it on a heavy cast iron base with sealed ball bearings. A splash guard, bumper ring, motor and a set of twelve 5/8 in nylon ball bearings are included. It weighs 250 lb, is made in the USA and has a one-year guarantee from the date of purchase.', features = '["Heavy duty sealed ball bearings", "Heavy cast iron base and lap plate", "Heavy duty 1/2 hp motor", "Splash guard", "Most compact Rociprolap model", "Holds up to 125 lb capacity", "Made in USA"]', included = '["Splash guard", "Bumper ring", "Motor", "One set of twelve 5/8\\" nylon ball bearings", "One set of 6 steel discs", "Polish pad", "Instructions"]', specs = '{"Weight": "250 lb", "Lap plate diameter": "20\\""}', warranty = 'Covington Engineering guarantees the machines for one year from the date of purchase against any defects (excludes nylon thrust bearings, steel discs and leveling feet).' WHERE id = 'covington-20-inch-rociprolap-flat-lap-machine';
UPDATE products SET blurb = 'The Covington 16 Inch Vibra Lap is an automatic vibrating flat lap that abrades and polishes with little attention, and holds up to 25 lb.

The plate is grooved to cut faster, a pad insert handles polishing, and the pan lifts out for cleaning. It is light, quiet, and has mounting holes for fixing it in place.', features = '["Removable pan for easy cleaning", "Grooved plate surface promotes faster cut", "Pad insert provides polishing capabilities", "Abrades and polishes with minimal assistance", "Light weight for portability", "Runs quietly", "Mounting holes for securing to work surface", "Heavy-duty cast aluminum construction", "Bumper ring helps prevent fracturing", "Most popular size", "Can be used on tabletop or work bench", "25 lb weight capacity"]', included = '[]', specs = '{"Weight capacity": "25 lb"}', warranty = NULL WHERE id = 'covington-16-inch-vibra-lap-automatic-vibrating-flat-lap-mac';
UPDATE products SET blurb = 'The Covington 12 Inch Vibra Lap is an automatic vibrating flat lap that abrades and polishes with little attention, and holds up to 20 lb.

The plate is grooved to cut faster, a pad insert handles polishing, and the pan lifts out for cleaning. It includes a motor, polish pad, bumper ring, instructions and the product guarantee.', features = '["Removable pan for easy cleaning", "Grooved plate surface promotes faster cut", "Pad insert provides polishing capabilities", "Abrades and polishes with minimal assistance", "Light weight for portability", "Runs quietly", "Mounting holes for securing to work area", "Heavy-duty cast aluminum construction", "Bumper ring helps prevent fracturing", "20 lb weight capacity"]', included = '["Motor", "Polish pad", "Bumper ring", "Instructions", "Product guarantee"]', specs = '{"Diameter": "12\\"", "Weight capacity": "20 lb"}', warranty = NULL WHERE id = 'covington-12-inch-vibra-lap-automatic-vibrating-flat-lap-mac';
UPDATE products SET blurb = 'The Covington 10 Inch Vibra Lap is an automatic vibrating flat lap that abrades and polishes with little attention, and holds up to 15 lb.

The plate is grooved to cut faster, a pad insert handles polishing, and the pan lifts out for cleaning. It is light, quiet and covered by the manufacturer\'s warranty.', features = '["Removable pan for easy cleaning", "Grooved plate surface promotes faster cut", "Pad insert provides polishing capabilities", "Abrades and polishes with minimal assistance", "Lightweight for portability", "Runs quietly", "Mounting holes for securing to work area", "Heavy-duty cast aluminum construction", "Bumper ring helps prevent fracturing", "15 lb weight capacity", "Made in USA"]', included = '[]', specs = '{"Diameter": "10\\"", "Weight capacity": "15 lb"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-10-inch-vibra-lap-automatic-vibrating-flat-lap-mac';
UPDATE products SET blurb = 'The Covington Triple Quart Rolling Rock Tumbler runs three solid LLDPE barrels at once, for 9 lb of material in total.

A fan-cooled motor drives them on steel support shafts and DuPont nylon bearings, in a cast aluminum chassis with a powder-coated frame and belt guard. Instructions and the manufacturer\'s warranty are included.', features = '["Three solid LLDPE barrels", "Cast aluminum chassis", "Powder coated frame and belt guard", "Steel support shafts", "DuPont nylon bearings", "Fan cooled motor", "9 lb total capacity", "Instructions included"]', included = '["Three solid LLDPE barrels (9 lb total capacity)", "Instructions"]', specs = '{"Capacity": "9 lb total"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-triple-quart-rolling-rock-tumbler';
UPDATE products SET blurb = 'The Covington Triple Gallon Rolling Rock Tumbler runs three solid LLDPE barrels at once, handling 36 lb in total.

The 35 in chassis is cast aluminum and steel, corrosion-resistant, with a powder-coated frame and belt guard, solid 1/2 in steel support shafts and DuPont nylon bearings. Instructions and the manufacturer\'s warranty are included.', features = '["Three solid LLDPE barrels", "35\\" cast aluminum and steel chassis", "Heavy duty cast aluminum construction for corrosion resistance", "Powder coated frame and belt guard", "Solid 1/2\\" steel support shafts", "DuPont nylon bearings", "Fan cooled 1/6 hp motor", "36 lb total capacity", "Instructions included"]', included = '["Instructions"]', specs = '{"Capacity": "36 lb total", "Chassis": "35\\" cast aluminum and steel"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-triple-gallon-rolling-rock-tumbler';
UPDATE products SET blurb = 'The Covington Single Half-Gallon Rolling Rock Tumbler turns one solid LLDPE barrel holding 6 lb.

A fan-cooled 1/21 hp motor drives it on solid 1/2 in steel support shafts with DuPont nylon bearings. The chassis is 11-1/2 in of cast aluminum and steel with a powder-coated frame and belt guard. Instructions and the manufacturer\'s warranty are included.', features = '["One solid LLDPE barrel", "11-1/2\\" cast aluminum and steel chassis", "Heavy duty cast aluminum construction", "Powder coated frame and belt guard", "Solid 1/2\\" steel support shafts", "DuPont nylon bearings", "Fan cooled 1/21 hp motor", "6 lb total capacity", "Instructions included"]', included = '["Instructions"]', specs = '{"Capacity": "6 lb"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-single-half-gallon-rolling-rock-tumbler';
UPDATE products SET blurb = 'The Covington Double Quart Rolling Rock Tumbler runs two solid LLDPE barrels, for 6 lb in total.

The cast aluminum chassis resists corrosion, the frame and belt guard are powder-coated, and a fan-cooled motor drives the barrels on steel shafts and DuPont nylon bearings. It is made in the USA, with instructions and the manufacturer\'s warranty.', features = '["Two solid LLDPE barrels", "Cast aluminum chassis for corrosion resistance", "Powder coated frame and belt guard", "Steel support shafts", "DuPont nylon bearings", "Fan cooled motor", "6 lb total capacity", "Instructions included", "Made in the USA"]', included = '["Instructions"]', specs = '{"Capacity": "6 lb total"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-double-quart-rolling-rock-tumbler';
UPDATE products SET blurb = 'The Covington Double Gallon Rolling Rock Tumbler runs two solid LLDPE barrels of 12 lb each, 24 lb in total.

The 24-1/2 in chassis is heavy cast aluminum and steel, corrosion-resistant, with a powder-coated frame and belt guard, solid 1/2 in steel shafts and DuPont nylon bearings. Instructions and the manufacturer\'s warranty are included.', features = '["Two solid LLDPE barrels", "24-1/2\\" cast aluminum and steel chassis", "Heavy duty cast aluminum construction for corrosion resistance", "Powder coated frame and belt guard", "Solid 1/2\\" steel support shafts", "DuPont nylon bearings", "Fan cooled, 1/6 hp, CSA certified motor", "24 lb total capacity", "Instructions included", "Made in the USA"]', included = '["Instructions"]', specs = '{"Capacity": "24 lb total (two 12 lb barrels)", "Chassis": "24-1/2\\" cast aluminum and steel"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-double-gallon-rolling-rock-tumbler';
UPDATE products SET blurb = 'The Covington Manual Gemstone Drill is a lever-operated drill with a 3/4 in stroke and a 1/15 hp, 5000 rpm motor controlled by a foot pedal.

It suits medium to soft gemstone material and glass. The bracket and motor adjust quickly for height, and the motor can be removed and mounted horizontally. A 1/4 in Jacobs chuck and key, a water pan and instructions are included, with the manufacturer\'s warranty.', features = '["Lever operated with 3/4\\" stroke", "1/15 hp, 5000 rpm motor", "Foot-operated variable speed control", "Ideal for medium to soft gemstone material or glass", "Bracket and motor quickly adjust for height", "Motor removes and mounts horizontally for buffer/carver conversion", "Made in USA"]', included = '["1/4\\" Jacobs chuck and key", "Water pan", "Instructions"]', specs = '{}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-manual-gemstone-drill';
