-- Batch 11 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'Phenolic Star and Cab Laps are 6 in phenolic laps, 3/8 in thick, with a 1/2 in arbor hole.', features = '["High quality", "3/8\\" thick", "6\\" diameter", "1/2\\" arbor hole"]', included = '[]', specs = '{"Diameter": "6\\"", "Thickness": "3/8\\"", "Arbor hole": "1/2\\""}', warranty = NULL WHERE id = 'phenolic-star-and-cab-laps';
UPDATE products SET blurb = 'The 50 Piece Diamond Carving Bur Set gives you 50 nickel-electroplated, 120 grit diamond burs in assorted shapes on 1/8 in shanks.

They arrive in a clear plastic case.', features = '["Variety of shapes", "Nickel electroplated", "120 grit diamond", "1/8\\" diameter shank", "Clear plastic case"]', included = '["50 diamond carving burs", "Clear plastic storage case"]', specs = '{}', warranty = NULL WHERE id = '50-piece-diamond-carving-bur-set';
UPDATE products SET blurb = 'The Diamond Burs 30 Piece Set fits any flex-shaft tool with a 3/32 in shank.

Each set holds 30 pieces in a clear plastic case. Choose 3.2 mm or 5.3 mm tips in 46, 120 or 240 grit.', features = '["Two tip sizes", "3/32\\" shaft", "Compatible with any flex shaft tool", "Pre-packaged in clear plastic case"]', included = '[]', specs = '{"Tip sizes": "3.2mm or 5.3mm", "Grit options": "46, 120, 240", "Quantity": "30 pieces per set"}', warranty = NULL WHERE id = 'diamond-burs-30-piece-set';
UPDATE products SET blurb = 'The Inland Glass Grinder Lamp Attachment is a LED lamp for Inland WizlingCG and WizCG grinders.

It attaches quickly and securely, has adjustable brightness and color temperature, and the LED is rated for 10,000 hours.', features = '["Compatible with Inland WizlingCG and WizCG grinders", "Secure, fast attachment", "Color temperature control", "Brightness control", "10,000 hour LED lifespan"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'inland-glass-grinder-lamp-attachment';
UPDATE products SET blurb = 'The Inland Sintered Diamond Bur in the Christmas Tree shape has diamond crystals evenly distributed through a durable binder rather than plated on the surface.

Inland says it lasts 5 to 10 times longer than plated burs. The shaft is 3/32 in and 35 mm long. Sizes are 5 x 13 mm and 6 x 13 mm, in 100, 220, 325 and 600 grit.', features = '["Uniform matrix of diamond crystals in durable binder", "Lasts 5-10x longer than diamond plated burs", "Lasts up to 100x longer than silicon carbide or aluminum oxide points", "3/32\\" shaft, 35mm long (excluding diamond portion)"]', included = '[]', specs = '{"Sizes": "5mm x 13mm, 6mm x 13mm", "Grits": "100, 220, 325, 600"}', warranty = NULL WHERE id = 'inland-sintered-diamond-bur-christmas-tree';
UPDATE products SET blurb = 'The Inland Sintered Diamond Bur in the Sharp Flame shape is a tapered bur with diamond distributed throughout the bond instead of plated on the outside.

The shaft is 3/32 in and 35 mm long. Available as 4 x 12 mm, 6 x 13 mm or 7 x 13 mm, in 100, 220, 325 and 600 grit.', features = '["Uniform matrix of diamond crystals in durable binder", "Lasts 5-10x longer than diamond plated burs", "Lasts up to 100x longer than silicon carbide or aluminum oxide points", "3/32\\" shaft, 35mm long (excluding diamond portion)"]', included = '[]', specs = '{"Sizes": "4mm x 12mm, 6mm x 13mm, 7mm x 13mm", "Grits": "100, 220, 325, 600"}', warranty = NULL WHERE id = 'inland-sintered-diamond-bur-sharp-flame';
UPDATE products SET blurb = 'The Inland Sintered Diamond Bur in the Round (ball) shape is a sintered bur that outlasts plated burs by a wide margin, according to Inland.

The 3/32 in shaft is 35 mm long. Sizes are 5 x 5 mm and 6 x 6 mm, in 100, 220, 325 and 600 grit.', features = '["Uniform matrix of diamond crystals in durable binder", "Lasts 5-10x longer than diamond plated burs", "Lasts up to 100x longer than silicon carbide or aluminum oxide points", "3/32\\" shaft, 35mm long (excluding diamond portion)"]', included = '[]', specs = '{"Sizes": "5mm x 5mm, 6mm x 6mm", "Grits": "100, 220, 325, 600"}', warranty = NULL WHERE id = 'inland-sintered-diamond-bur-round';
UPDATE products SET blurb = 'The Inland Sintered Diamond Bur in the Round Head Cylinder shape has a straight side and a rounded end.

The 3/32 in shaft is 35 mm long. Sizes are 4 x 12 mm, 6 x 13 mm and 8 x 13 mm, in 100, 220, 325 and 600 grit.', features = '["Uniform matrix of diamond crystals in durable binder", "Lasts 5-10x longer than diamond plated burs", "Lasts up to 100x longer than silicon carbide or aluminum oxide points", "3/32\\" shaft, 35mm long (excluding diamond portion)"]', included = '[]', specs = '{"Sizes": "4mm x 12mm, 6mm x 13mm, 8mm x 13mm", "Grits": "100, 220, 325, 600"}', warranty = NULL WHERE id = 'inland-sintered-diamond-bur-round-head-cylinder';
UPDATE products SET blurb = 'The Inland Sintered Diamond Bur in the Round Head Cone shape tapers to a rounded tip.

The 3/32 in shaft is 35 mm long. Sizes are 4 x 11 mm, 6 x 13 mm and 8 x 13 mm, in 100, 220, 325 and 600 grit.', features = '["Uniform matrix of diamond crystals in durable binder", "Lasts 5-10x longer than diamond plated burs", "Lasts up to 100x longer than silicon carbide or aluminum oxide points", "3/32\\" shaft, 35mm long (excluding diamond portion)"]', included = '[]', specs = '{"Sizes": "4mm x 11mm, 6mm x 13mm, 8mm x 13mm", "Grits": "100, 220, 325, 600"}', warranty = NULL WHERE id = 'inland-sintered-diamond-bur-round-head-cone';
UPDATE products SET blurb = 'The Inland Sintered Diamond Bur in the Pearl shape is an oval, rounded bur.

Diamond is spread through the bond rather than plated on, so it keeps cutting as it wears. The 3/32 in shaft is 35 mm long. Sizes are 4 x 10 mm, 6 x 13 mm and 8 x 13 mm, in 100, 220, 325 and 600 grit.', features = '["Uniform matrix of diamond crystals in durable binder", "Lasts 5-10x longer than diamond plated burs", "Lasts up to 100x longer than silicon carbide or aluminum oxide points", "3/32\\" shaft, 35mm long (excluding diamond portion)"]', included = '[]', specs = '{"Sizes": "4mm x 10mm, 6mm x 13mm, 8mm x 13mm", "Grits": "100, 220, 325, 600"}', warranty = NULL WHERE id = 'inland-sintered-diamond-bur-pearl';
