UPDATE products SET blurb = 'Covington Platinum 301 Diamond Saw Blades are sintered blades made for hard material such as agate, petrified wood and jade.

Compared with standard blades they carry a higher diamond concentration and a higher-carbon steel core that holds tension better. The sintered diamond kerf is solid, which helps both cutting speed and coolant flow. Shipping is free within the lower 48 states.', features = '["Higher diamond concentration", "Higher carbon content steel core for improved tension memory", "Solid diamond sintered kerf for better cutting performance and coolant flow", "Excellent for hard materials: agate, petrified wood, jade", "FREE Shipping (lower 48 states)"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'covington-platinum-301-diamond-saw-blades';
UPDATE products SET blurb = 'Covington Diamond Compound is a diamond paste sold in 5 gram and 10 gram graduated syringes, in a range of mesh and micron grades.

Pair it with Diamond Extender Fluid to keep the paste from overheating as you work.', features = '["5 gram and 10 gram graduated syringes", "Multiple mesh/micron grades available", "Use with Diamond Extender Fluid to prevent overheating"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'covington-diamond-compound';
UPDATE products SET blurb = 'Cerium Oxide #1 Standard is a polishing powder for quartz, agate, opal, obsidian and similar stones.

It polishes faster than conventional compounds without staining or caking. Use it on leather when polishing stone and on felt when polishing glass. Available in 1 lb, 5 lb and 44 lb sizes.', features = '["Polishes quartz, agate, opal, obsidian and more", "Faster polishing rate than conventional compounds", "No staining or caking", "Works best with leather (stone) or felt (glass)", "Available in 1 lb, 5 lb, 44 lb"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'cerium-oxide-1-standard';
UPDATE products SET blurb = 'The Covington Standard Diamond Grinding Wheel is a heavy-duty, nickel-electroplated solid steel wheel, 1-1/2 in wide.

A stack bushing is included and fits 1/2 in, 5/8 in, 3/4 in and 1 in shafts, so it will mount on most grinders.', features = '["Heavy duty", "Solid steel", "Nickel electroplated", "1-1/2\\" in width", "Stack bushing included"]', included = '["Stack bushing for shaft sizes: 1/2\\", 5/8\\", 3/4\\", and 1\\""]', specs = '{"Width": "1-1/2\\""}', warranty = NULL WHERE id = 'covington-standard-diamond-grinding-wheel';
UPDATE products SET blurb = 'REZ Diamond Wheels are soft resin-bond diamond wheels for cabbing and contour grinding.

The resin binder and diamond abrasive cut smoothly on curves and around the edge of a cab. The arbor hole is 1 in and a bushing is included. Like most resin wheels, they need a short break-in before they cut at their best.', features = '["Soft wheel for cabbing and contour grinding", "Premium resin binder", "High-quality diamond abrasive", "1\\" arbor hole with bushing included", "Requires a break-in period"]', included = '["Bushing"]', specs = '{"Arbor hole": "1\\""}', warranty = NULL WHERE id = 'rez-diamond-wheels';
UPDATE products SET blurb = 'The Gemini Apollo Ring Saw is a compact 1/3 hp ring saw that cuts material over 3 in thick and can slice tile up to 16 in on the diagonal.

Gemini rates its torque at ten times that of a standard tile saw. The blades ride in removable cartridges, and the saw comes with a slide tray, magnetic angle guides and mounting hardware. It weighs 32 lb and measures 11 in high by 20 in wide by 21 in deep. Free shipping applies.', features = '["Delivers 10x the torque of standard tile saws", "Slices materials over 3 inches thick", "Can cut tile up to 16\\" diagonally", "Removable blade cartridges", "1/3 hp motor", "Slide tray", "Magnetic angles", "Mounting hardware", "FREE Shipping"]', included = '["Mounting hardware", "Slide tray"]', specs = '{"Weight": "32 lb", "Dimensions": "11\\" H x 20\\" W x 21\\" D"}', warranty = NULL WHERE id = 'gemini-apollo-ring-saw';
