-- Batch 14 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'The Inland Bandsaw Blade for Metal cuts thin brass, copper, zinc, aluminum, tin and other nonferrous metals, plus fiberglass, leather, acrylic and circuit boards.

It is 37.7 in long with 24 teeth per inch and 0.012 in thickness, and fits the Inland Craft DB-100 band saw.', features = '["For thin brass, copper, zinc, aluminum, tin, nonferrous metals, fiberglass, leather, acrylic, circuit boards", "Precision-cut for smooth, fast sawing", "Fits Inland Craft DB-100 band saw"]', included = '[]', specs = '{"Length": "37.7\\"", "Teeth per inch": "24", "Thickness": "0.012\\"", "Depth": "0.13\\""}', warranty = NULL WHERE id = 'inland-bandsaw-blade-for-metal';
UPDATE products SET blurb = 'The Inland Bandsaw Blade for Wood cuts wood, wood composites, acrylic, leather, polyethylene and polycarbonate.

It is 37.7 in long with 14 teeth per inch and a 0.22 in width, and fits the Inland Craft DB-100 band saw.', features = '["For wood, wood composites, acrylic, leather, polyethylene, polycarbonate", "Precision-cut for smooth, fast sawing", "Fits Inland Craft DB-100 band saw"]', included = '[]', specs = '{"Length": "37.7\\"", "Teeth per inch": "14", "Width": "0.22\\"", "Kerf": "~0.32\\"", "Depth": "0.013\\""}', warranty = NULL WHERE id = 'inland-bandsaw-blade-for-wood';
UPDATE products SET blurb = 'The Inland Diamond Band Saw Blade has diamond bonded to a stainless steel band, for wet sawing of glass, stone, gems, tile, ceramic and more.

It is 37.7 in long and 0.022 in thick, cuts a kerf of about 0.030 in, and fits the Inland Craft DB-100 band saw.', features = '["Diamond bonded to stainless steel", "For wet sawing glass, stone, gems, tile, ceramic and more", "Fits Inland Craft DB-100 band saw"]', included = '[]', specs = '{"Length": "37.7\\"", "Depth": "0.130\\"", "Thickness": "0.022\\"", "Kerf": "~0.030\\""}', warranty = NULL WHERE id = 'inland-diamond-band-saw-blade';
UPDATE products SET blurb = 'The Inland DB-100 Band Saw is a compact tabletop band saw with a permanent-magnet DC motor and speed control up to 3,400 rpm.

A five-part spring-loaded tensioning system holds the blade, and the pre-assembled coolant system has a control valve and internal drain channels so coolant is not recirculated. An adjustable upper drip guide is fitted. In the box are a 37.7 in stainless steel diamond blade, two BladeSert blade guides and a leather blade wiper. It runs on 115V, measures 13 x 10 x 18 in and weighs 10 lb. The warranty is one year, or 90 days in salt-water environments.', features = '["Permanent magnet DC motor with speed control, up to 3,400 rpm", "Five-part spring-loaded tension system", "Pre-assembled coolant system with control valve", "Internal drain channels prevent coolant recirculation", "Adjustable upper drip guide", "9\\" x 10.75\\" corrosion resistant work surface", "Structural-grade thermoplastic frame", "Lightweight, portable, sound-dampening housing"]', included = '["37.7\\" stainless steel diamond band saw blade", "Two BladeSert blade guides", "Leather blade wiper", "Instruction manual"]', specs = '{"Dimensions": "13\\" L x 10\\" W x 18\\" H", "Weight": "10 lb", "Voltage": "115V", "Torque": "48 oz-in", "Work surface": "9\\" x 10.75\\"", "Blade throat depth": "4.75\\"", "Max cutting thickness": "3\\" rocks/minerals, 1\\" solid glass slabs", "Cutting speed": "Up to 12 in/min"}', warranty = 'One-year warranty (90-day in salt water environments)' WHERE id = 'inland-db-100-band-saw';
UPDATE products SET blurb = 'The CabKing Canvas Polishing Pad is a 6 in untreated canvas pad for polishing stone, glass and synthetics.

The back has a 1/4-20 thread for mounting.', features = '["Polishes stone, glass & synthetics", "Untreated canvas material", "6\\" diameter", "1/4\\"-20 thread on back"]', included = '[]', specs = '{"Diameter": "6\\"", "Thread": "1/4\\"-20"}', warranty = NULL WHERE id = 'cabking-canvas-polishing-pad';
UPDATE products SET blurb = 'The Pro-Flow Water Cooling System for Slant Cabber enlarges the water reservoir on Slant Cabber machines built after January 1, 2017.

It can be run from a pressure tank or a water pump, using 1/4 in outside-diameter tubing.', features = '["Increases water reservoir capacity", "Pressure tank or water pump options", "For Slant Cabber machines made after Jan 1, 2017"]', included = '[]', specs = '{"Tubing outer diameter": "1/4\\""}', warranty = NULL WHERE id = 'pro-flow-water-cooling-system-for-slant-cabber';
UPDATE products SET blurb = 'The Hi-Tech Diamond Pro-Flow Water Cooling System for the All-U-Need Lap Machine adds reservoir capacity, and works with either a pressure tank or a water pump.

The kit includes a 5 in Pro-Flow attachment tube (1/4 in OD) and a long 5/8 in drain tube to replace the original short one. It is for All-U-Need machines only.', features = '["Increases water reservoir capacity", "Pressure tank or water pump options", "For All-U-Need machines only"]', included = '["Pro-Flow attachment tube", "Long drain tube (replaces original short tube)"]', specs = '{"Attachment tube OD": "1/4\\"", "Attachment tube length": "5\\"", "Drain tube OD": "5/8\\"", "Drain tube length": "4-1/2\\""}', warranty = NULL WHERE id = 'hi-tech-diamond-pro-flow-water-cooling-system-for-all-u-need-lap-machine';
UPDATE products SET blurb = 'Hi-Tech Diamond Final Polishing Pads arrive pre-charged with cerium oxide, so there is nothing to mix and no mess.

They polish both stone and glass, stick on with 3M pressure-sensitive adhesive, and come in 6 in and 8 in sizes with a 1/2 in arbor hole.', features = '["Pre-charged with cerium oxide", "Mess-free", "Works on stones and glass", "3M pressure-sensitive adhesive backing"]', included = '[]', specs = '{"Diameters": "6\\", 8\\"", "Arbor hole": "1/2\\""}', warranty = NULL WHERE id = 'hi-tech-diamond-final-polishing-pads';
UPDATE products SET blurb = 'Hi-Tech Diamond Tech-11 Polishing Pads are 1/8 in thick pads of high-density natural wool felt with 3M pressure-sensitive adhesive on the back.

Sizes are 6 in and 8 in, both with a 1/2 in arbor hole.', features = '["High-density all-natural wool felt", "1/8\\" thick", "3M pressure-sensitive adhesive backing"]', included = '[]', specs = '{"Diameters": "6\\", 8\\"", "Arbor hole": "1/2\\""}', warranty = NULL WHERE id = 'hi-tech-diamond-tech-11-polishing-pads';
UPDATE products SET blurb = 'Hi-Tech Diamond Diamond Compound Paste comes in disposable syringes of 2, 5 or 10 grams, color-coded by grit.

Grits run from 220 up to 100,000. The carrier is oil-based, except for the 14K, 50K and 100K grades, which are water-based.', features = '["Oil-based carrier (water-based for 100k, 50k, 14k grits)", "Color-coded by grit", "Disposable syringe packaging"]', included = '[]', specs = '{"Sizes": "2g, 5g, 10g", "Grits": "220, 325, 600, 1200, 3000, 8000, 14000, 50000, 100000"}', warranty = NULL WHERE id = 'hi-tech-diamond-diamond-compound-paste';
