-- Batch 37 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'Covington Nickel Bonded Diamond Domes have a dome-shaped grinding surface about 3-7/8 in across the base and 1-1/2 in tall.

A 3/16 in center hole supports through-shaft water systems. Female threads are 5/8-11 or 1-14.', features = '["Nickel bonded diamond construction", "Dome-shaped grinding surface", "3/16\\" center hole for through-shaft water systems"]', included = '[]', specs = '{"Size": "approx. 3-7/8\\" base x 1-1/2\\" height", "Thread sizes": "5/8\\"-11 female or 1\\"-14 female", "Grits": "Coarse (100g), Medium (220g), Fine (600g)"}', warranty = NULL WHERE id = 'covington-nickel-bonded-diamond-domes';
UPDATE products SET blurb = 'The Gemini Revolution XT Belt Tensioner is a replacement part for the Gemini Revolution XT ring saw.', features = '["Replacement part for Gemini Revolution XT"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'gemini-revolution-xt-belt-tensioner';
UPDATE products SET blurb = 'The Covington Magnetic Disc Organizer is a wall-mountable heavy-duty metal organizer with galvanized steel pages that hold magnetic discs.

It has a powder-coated back and comes in 12, 18 and 24 in sizes.', features = '["Heavy-duty metal", "Powder coated back", "Galvanized steel pages", "Wall mountable"]', included = '[]', specs = '{"Sizes": "12\\", 18\\", 24\\""}', warranty = NULL WHERE id = 'covington-magnetic-disc-organizer';
UPDATE products SET blurb = 'The Leg Stand for Covington\'s 12 Inch Flat Lap Horizontal Beveler is a welded, powder-coated stand, 12 in high on a 22 in square base, made to fit the 12 in beveler.', features = '["12\\" high x 22\\" square", "Fits 12\\" Beveler unit perfectly", "Welded and powder coated"]', included = '[]', specs = '{"Height": "12\\"", "Base": "22\\" square"}', warranty = NULL WHERE id = 'leg-stand-for-covington-s-12-inch-flat-lap-horizontal-bevele';
UPDATE products SET blurb = 'The Covington Flat Lap Beveler Grinder Replacement Plate is a machined and ground plate with a 1 in smooth bore and four 1/4 in countersunk mounting holes.

Sizes are 12, 18 and 24 in.', features = '["1\\" smooth bore hole, machined to precise tolerances", "Blanched and ground surface for tight tolerances", "Four 1/4\\" countersunk mounting holes"]', included = '[]', specs = '{"Sizes": "12\\", 18\\", 24\\""}', warranty = NULL WHERE id = 'covington-flat-lap-beveler-grinder-replacement-plate';
UPDATE products SET blurb = 'The Covington Flat Lap Beveler and Grinder Bottle Kit is a starter set for bottle work.

It includes a fine diamond cone, a felt polishing cone and grinding discs starting at 100 and 270 grit.', features = '["Complete starter kit for bottle work"]', included = '["1 Fine Diamond Cone", "1 Felt Polishing Cone", "1 x 100 Grit Grinding Disc", "1 x 270 Grit Grinding Disc", "1 x 325 Resin Bonded Disc", "1 Felt Magnetic Backed Polishing Disc", "1 lb of Cerium Oxide (Optical Grade)"]', specs = '{}', warranty = NULL WHERE id = 'covington-flat-lap-beveler-and-grinder-bottle-kit';
UPDATE products SET blurb = 'The Covington Flat Lap Beveler and Grinder Disc Kit collects the discs used most often on a beveler grinder.

It includes 100 and 270 grit grinding discs, a 325 resin-bonded disc and a felt polishing disc.', features = '["Covers the most commonly used discs for a beveler grinder"]', included = '["1 x 100 Grit Grinding Disc", "1 x 270 Grit Grinding Disc", "1 x 325 Resin Bonded Disc", "1 Felt Polishing Disc", "1 lb of Cerium Oxide (Optical Grade)"]', specs = '{}', warranty = NULL WHERE id = 'covington-flat-lap-beveler-and-grinder-disc-kit';
UPDATE products SET blurb = 'The Covington Flat Lap Beveler and Grinder New User Kit is a starter package that includes a submersible pump with 10 ft of 1/4 in tubing and grinding discs starting at 100 and 270 grit.

The 12 in kit also includes a stand for the beveler grinder.', features = '["Complete new-user starter kit", "12\\" kit includes a beveler grinder stand"]', included = '["1 Submersible Pump with 10\' x 1/4\\" tubing", "1 x 100 Grit Grinding Disc", "1 x 270 Grit Grinding Disc", "1 x 325 Resin Bonded Disc", "1 Felt Polishing Disc", "1 lb of Cerium Oxide (Optical Grade)", "1 Beveler Grinder Stand (12\\" kit only)"]', specs = '{}', warranty = NULL WHERE id = 'covington-flat-lap-beveler-and-grinder-new-user-kit';
UPDATE products SET blurb = 'The Covington 12 Inch Flat Lap Beveler and Grinder is built on a heavy welded steel chassis with a 1 in stainless steel shaft, welded flange and heavy-duty ball bearings.

The shaft accepts 5/8-11 RH male accessories. An aluminum water manifold controls fluid flow, and a stainless steel splash guard and brush are included. It measures 25 x 25 x 27 in and weighs 185 lb.', features = '["Aluminum water manifold controls fluid flow", "Heavy welded steel chassis", "Stainless steel splash guard and brush", "Shaft accepts 5/8\\"-11RH male accessories", "1\\" stainless steel shaft with welded flange", "Heavy-duty ball bearings", "Single Speed & Variable Speed options", "Water supply through dual overhead loc-line and shaft center (variable speed)"]', included = '[]', specs = '{"Weight": "185 lb", "Width": "25\\"", "Height": "27\\"", "Depth": "25\\""}', warranty = NULL WHERE id = 'covington-12-inch-flat-lap-beveler-and-grinder';
UPDATE products SET blurb = 'The Covington 24 Inch Flat Lap Beveler and Grinder is the largest in the line, on a heavy welded steel chassis with a 1 in stainless steel shaft and heavy-duty ball bearings.

The shaft accepts 5/8-11 RH male accessories, an aluminum manifold controls water, and a stainless steel splash guard and brush are included. It weighs 425 lb (lift-gate delivery is available for an added charge) and is 35 in wide.', features = '["Aluminum water manifold controls fluid flow", "Heavy welded steel chassis", "Stainless steel splash guard and brush", "Shaft accepts 5/8\\"-11RH male accessories", "1\\" stainless steel shaft with welded flange", "Heavy-duty ball bearings", "Single Speed and Variable Speed options", "Water supply through shaft center and dual overhead loc-line"]', included = '[]', specs = '{"Weight": "425 lb (lift-gate service available for additional charge)", "Width": "35\\"", "Height": "35\\"", "Depth": "48\\""}', warranty = NULL WHERE id = 'covington-24-inch-flat-lap-beveler-and-grinder';
