-- Batch 17 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'Covington Drain Kits attach to vertical sanders and grinder machines to drain water out of the pans.

Versions are available for 3/8 in and 1/4 in fittings and for the Maxi Lap.', features = '["Attaches to vertical sanders and grinder machines", "Drains water from pans", "Available in 3/8\\", 1/4\\", and Maxi Lap versions"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'covington-drain-kits';
UPDATE products SET blurb = 'The Covington 2-Gallon Pressure Water Tank supplies a steady, pressurized flow of water to your machine.

It holds 2 gallons and is light and durable.', features = '["Steady pressurized water supply", "Durable, lightweight design", "2 gallon capacity"]', included = '[]', specs = '{"Capacity": "2 gallons"}', warranty = NULL WHERE id = 'covington-2-gallon-pressure-water-tank';
UPDATE products SET blurb = 'The Covington 18 Inch Heavy Duty Slab Saw is a welded-steel slab saw with a six-speed power feed, automatic shut-off and a quick-return system.

An over-running clutch adjusts from soft to hard rock, and the powder-coated chassis weighs 325 lb. A 9 in vise, motor and an A-Series Signature blade are included.', features = '["A-Series Signature Blade included", "9\\" vise included", "Powder coated, heavy welded steel chassis", "6-speed power feed with automatic shut-off", "Quick return system", "Over-running clutch, soft to hard rock", "8\\" cross feed capacity without re-clamping", "One piece arbor and flange", "Heavy-duty neoprene sealed ball bearings, greased for life"]', included = '["9\\" vise", "Motor", "Covington\'s Best Diamond Blade (A-Series Signature Blade)"]', specs = '{"Weight": "325 lb"}', warranty = NULL WHERE id = 'covington-18-inch-heavy-duty-slab-saw';
UPDATE products SET blurb = 'The Covington Large Basic Wet Belt Sander is a build-your-own wet belt sander that takes 3 x 41-1/2 in belts.

The work area is unobstructed, belts change quickly, and the back plate adjusts. The hood, base and bearing support are powder-coated, and the bearings are shielded, double sealed and greased for life. Manufacturer\'s warranty applies.', features = '["Build-your-own style", "Unobstructed access to work area", "Quick change belt system", "3\\" x 41-1/2\\" belts", "Powder coated hood, base, and bearing support", "Shielded bearings, double sealed, greased for life", "Adjustable back plate"]', included = '[]', specs = '{"Belt size": "3\\" x 41-1/2\\""}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-large-basic-wet-belt-sander';
UPDATE products SET blurb = 'The Covington 36 Inch Slab Saw is Covington\'s largest slab saw, a 1,200 lb machine that runs on 220V/60Hz only.

It has a heavy welded steel chassis, six-speed power feed with automatic shut-off, quick-return system, an over-running clutch for soft to hard rock and 8 in of cross-feed capacity. The arbor and flange are one piece. A vise, motor and Covington Platinum blade are included.', features = '["220V, 60Hz only", "Powder coated, heavy welded steel chassis", "6-speed power feed with automatic shut-off", "Quick return system", "Over-running clutch, soft to hard rock", "8\\" cross feed capacity", "One-piece arbor and flange", "Neoprene-sealed, lifetime-greased ball bearings"]', included = '["Vise", "Motor", "Covington Platinum Blade"]', specs = '{"Weight": "1,200 lb"}', warranty = NULL WHERE id = 'covington-36-inch-slab-saw';
UPDATE products SET blurb = 'The Covington Basic Wet Belt Sander is a build-your-own wet belt sander for 3 x 24 in belts.

Belts change quickly, the work area is open, and the back plate adjusts. The hood, base and bearing support are powder-coated, and the bearings are double sealed, shielded and greased for life. Manufacturer\'s warranty applies.', features = '["Build your own style", "Unobstructed access to work area", "Quick change belt system", "3\\" x 24\\" belts", "Powder coated hood, base, and bearing support", "Shielded bearings, double sealed, greased for life", "Adjustable back plate"]', included = '[]', specs = '{"Belt size": "3\\" x 24\\""}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-basic-wet-belt-sander';
UPDATE products SET blurb = 'The Covington 8 Inch Grinder Polisher is a diamond-equipped grinding and polishing unit with a 1/2 hp motor and speed control adjustable in 8 rpm steps.

It includes two 8 x 1-1/2 in metal-bond diamond wheels (100 and 220 grit), two 3 x 8 in diamond belts (325 and 1,200 grit), an 8 in aluminum head with leather disc and an 8 in expandable drum. A 5 gram syringe of 50,000 mesh diamond compound and a 2 oz bottle of extender fluid are supplied. The footprint is 36 x 24 in and it weighs 200 lb.', features = '["Two 8\\" x 1-1/2\\" metal-bond diamond grinding wheels (100g & 220g)", "Two 3\\" x 8\\" diamond belts (325g & 1,200g)", "8\\" aluminum head with leather disc", "8\\" expandable drum", "Speed control with 8 rpm changes", "1/2 hp heavy duty motor", "Rustproof aluminum-topped Lam-I-Cushion base", "Heavy-duty neoprene sealed ball bearings, greased for life"]', included = '["5-gram syringe of 50,000 mesh diamond compound", "2-ounce bottle of extender fluid", "Sample kit (polish powder, brush, dop sticks, wax)", "Book about using diamond abrasives", "Instructions"]', specs = '{"Footprint": "36\\" x 24\\"", "Weight": "200 lb"}', warranty = NULL WHERE id = 'covington-8-inch-grinder-polisher-diamond';
UPDATE products SET blurb = 'The Covington Heavy Duty Grinder Polisher is a quiet, high-torque machine with a 1/2 hp motor that accepts 6 in and 8 in wheels.

The arbor, pans and hoods are heavy-duty powder-coated aluminum, and the shaft is a turned, ground and polished 1 x 18 in piece. It works with 8 in aluminum heads and expandable drums and rides on neoprene-sealed ball bearings. Flanges, nuts, drive pulley, V-belt, belt guard, water valves and drains are included. The footprint is 22 x 24 in.', features = '["1/2 hp high-torque motor", "Runs quietly", "Heavy-duty powder coated aluminum arbor, pans, hoods", "1\\" x 18\\" turned, ground & polished shaft", "Accommodates 6\\" & 8\\" wheels", "8\\" aluminum heads and expandable drums", "Neoprene sealed ball bearings, greased for life"]', included = '["Flanges", "Nuts", "Drive pulley", "V-belt", "Belt guard", "Water valves", "Drains"]', specs = '{"Footprint": "22\\" x 24\\""}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-heavy-duty-grinder-polisher';
UPDATE products SET blurb = 'The Covington Vertical Glass Beveler has a 1/2 hp motor and takes 6 in, 8 in and 10 in wheels.

An adjustable sponge bench limits splash, the back plate has a spray nozzle, and the tank sides come off to make wheel changes easy. Neoprene-sealed ball bearings are greased for life and the base is rustproof. It has a belt guard and manufacturer\'s warranty.', features = '["Adjustable sponge bench minimizes splash", "Back plate with spray nozzle", "Fits 6\\", 8\\", and 10\\" wheels", "Removable tank sides for easy wheel change", "Neoprene sealed ball bearings, greased for life", "Rustproof base", "1/2 hp motor", "Belt guard"]', included = '[]', specs = '{}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-vertical-glass-beveler';
UPDATE products SET blurb = 'The Covington Felt Polishing Dome polishes the inside edges of glassware and, used with cerium oxide, produces an optically clear finish.

It screws onto Covington flat lap machines with the supplied 5/8-11 threaded brass adapter. The dome is about 4-1/2 in across at the base and 1-1/2 in tall.', features = '["For polishing interior edges of glassware", "Works with cerium oxide for optically clear finish", "Threaded brass adapter for flat lap machines"]', included = '["5/8\\"-11 threaded brass adapter"]', specs = '{"Base diameter": "~4-1/2\\"", "Height": "1-1/2\\""}', warranty = NULL WHERE id = 'covington-felt-polishing-dome';
