-- ============================================================================
-- Product content pass. The 'blurb' descriptions are original text written
-- for Bedrock Lapidary (not copied from any other site). features/included/
-- specs remain short factual lists. Run after
-- seed_products.sql. Safe to re-run (each statement is a full overwrite).
-- Batch 1 of an ongoing pass over the catalog.
-- ============================================================================

SET NAMES utf8mb4;

UPDATE products SET blurb = 'The CabKing 8 Inch Grinder Polisher is an eight-station cabbing machine driven by a 3/4 hp, 1800 rpm direct-drive motor.

Six wheel positions and two end stations give you room to run coarse-to-fine stages side by side, with a shut-off valve above each wheel so water goes only where you are working. A clean-water system keeps grit from one stage from contaminating the next, and a built-in lamp lights the work area. It ships with metal- and resin-bond diamond wheels from 80 to 3000 grit, a 360 grit flat lap, a canvas polishing pad, diamond paste, a separate submersible pump, splash hoods, pans, hand rests, goggles and an apron. Footprint is about 40 in wide by 13 in deep and it weighs roughly 75 lb. The motor and parts carry a one-year manufacturer\'s warranty (wheels excluded).', features = '["Direct Drive, 110/115V, 3/4 hp, 1800 rpm Motor", "Individual Water Shut Off Valves Above Each Wheel and Grinding/Polishing Pad", "8 Work Stations, 6 Wheels and 2 End Stations", "Clean Water System Provides Contamination Free Work Stations", "6W, 12V Lamp", "1 Year manufacturer\'s warranty on motor and parts (wheels not covered)", "FREE Shipping!"]', included = '["Two 8\\" x 1-1/2\\" metal bonded diamond wheels (80 and 220 grit)", "Four (1 wheel of each grit) 8\\" x 2\\" resin bonded diamond wheels (280, 600, 1200, and 3000 grit)", "One 8\\" 1/2\\" diamond flat lap (360 grit)", "One 5-1/2\\" no-hole canvas polishing pad", "One 2-gram syringe of diamond paste compound (14,000 grit)", "Goggles", "Apron", "Separate 605 GPH, 30W submersible pump", "Stainless steel splash hoods", "Adjustable clear splash shields", "Plastic pans with drain holes", "Side splash guards", "Metal hand rests"]', specs = '{"Weight": "75.00 lb", "Width": "40 inches", "Height": "14 inches", "Depth": "13 inches"}', warranty = '1 Year manufacturer\'s warranty on motor and parts (wheels not covered)' WHERE id = 'cabking-8-inch-grinder-polisher';
UPDATE products SET blurb = 'The Gemini Revolution XT Ring Saw slices tile and stone up to 6 cm thick with a 10 inch sintered diamond blade.

Because the blade is a ring rather than a disc, the length and width of the piece you can pass through it are effectively unlimited, and the saw cuts in both directions, which makes inside and outside curves easy to follow. It is fully self-contained and needs no water pump. The kit includes the saw, a slide tray, the stand assembly and your choice of single- or double-sided blade. The footprint is roughly 31 x 20 x 13 in.', features = '["Can cut forwards and backwards (makes curves simple to cut)", "Uses a 10 inch Sintered Diamond Blade (Single-sided and Double-sided blades available)", "Cut inside and outside radius curves", "Endless length and width capability", "Cuts tile and stone up to 6 cm thick", "No water pump, completely self-contained", "Heavy duty, yet portable", "Measures 31\\" x 20\\" x 13\\"", "FREE Shipping!"]', included = '["XT Revolution Ring Saw", "Slide Tray Kit", "Stand Assembly", "Your Choice of Blade"]', specs = '{"Dimensions": "31\\" x 20\\" x 13\\"", "Max material thickness": "6 cm", "Blade size": "10\\" Sintered Diamond Blade"}', warranty = NULL WHERE id = 'gemini-revolution-xt-ring-saw';
UPDATE products SET blurb = 'The Covington 40 Pound Production Rock Tumbler is built for shops that polish stone in volume rather than by the handful.

A 1/3 hp motor turns a powder-coated hexagonal barrel with a rubber liner, about 9 in across and 11 in deep inside, on dual rubber-covered 5/8 in steel shafts. The chassis is powder-coated steel with heavy-duty sealed ball bearings. It comes with instructions, the manufacturer\'s warranty and a sample of Old Miser.', features = '["1/3 hp motor", "Powder coated steel chassis", "Heavy duty sealed ball bearings", "Powder coated hexagonal barrel with rubber liner", "Barrel inner dimensions are approximately 9\\" across and 11\\" deep", "Dual driven, rubber covered, 5/8\\" steel support shafts"]', included = '["Sample of Old Miser", "Instructions", "Manufacturer\'s warranty"]', specs = '{"Barrel (inner)": "~9\\" across x 11\\" deep", "Motor": "1/3 hp"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-40-pound-production-rock-tumbler';
UPDATE products SET blurb = 'The Covington Bead Mill grinds round beads from 5/16 in to 3/4 in in diameter, up to 20 half-inch beads in one load.

It runs on a 1/3 hp, 110V motor in a dual-speed configuration, 380 rpm and 250 rpm, inside a powder-coated heavy-gauge steel housing. The chamber head lifts off quickly for cleaning. It measures about 24 in wide, 16 in tall and 12 in deep and weighs 75 lb. Instructions and the manufacturer\'s warranty are included.', features = '["Makes beads from 5/16\\" to 3/4\\" in diameter", "1/3 hp 110V, 60 Hz Motor", "Small Portable Size", "Mounted in a Heavy Gauge Powder-Coated Steel Housing", "Chamber head removes quickly for easy cleaning", "Grinds up to 20 half inch beads at a time", "Dual Speed model runs at 380 rpm and 250 rpm", "Instructions included", "Manufacturer\'s warranty", "FREE Shipping"]', included = '["Instructions"]', specs = '{"Weight": "75 lb", "Width": "24 inches", "Height": "16 inches", "Depth": "12 inches"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-bead-mill';
UPDATE products SET blurb = 'The Covington Large Sphere Machine turns rough stone into spheres from 1-1/4 in up to 9 in across.

Two 1/3 hp motors drive spring-loaded cutting heads with an adjustable cutting angle. Grit is applied automatically from a slurry bowl, and shielded arbor shafts and bearings keep abrasive out of the works. It sits in a large metal cabinet with a shelf, weighs about 250 lb, and comes with two 8 in spiral polishing buffs, two grit pans, the slurry bowl and one pair of cutter cups in the size you choose.', features = '["Makes Spheres From 1-1/4\\" to 9\\" in Diameter", "Dual 1/3 hp Motors", "Two 8\\" x 1/4\\" x 1\\" Spiral Polishing Buffs", "Two Grit Pans", "Automatic Grit Application With Slurry Bowl", "Spring Loaded Cutting Heads", "Cutting Angle Adjustment", "Shielded Arbor Shafts and Bearings", "Large Metal Cabinet with Shelf", "Powder Coated for Durability & Rust Resistance", "Made in USA", "FREE Shipping"]', included = '["Two 8\\" x 1/4\\" x 1\\" spiral polishing buffs", "Two grit pans", "Slurry bowl", "One pair of cutter cups (choice of: 1\\", 1-3/8\\", 2-3/8\\", 3-3/8\\" or 4-3/8\\")", "Large metal cabinet with shelf", "Instructions"]', specs = '{"Weight": "250 lb"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-large-sphere-machine';
UPDATE products SET blurb = 'The Covington Professional Glass Lathe is a variable-speed lathe for glass work, with 12 in of reach and a 1 hp DC motor that runs from 0 to 1850 rpm.

The frame is solid billet aluminum, and the shaft is turned, ground and polished stainless steel to keep vibration down. The spindle is 1 in with a Morse 3 taper, a drift key is supplied, and the water-resistant motor is controlled from a NEMA 4X box with a 5 ft power cord. It is a quiet machine for its class.', features = '["12\\" of reach", "Turned, ground and polished shaft minimizes vibration", "Morse 3 taper", "1\\" spindle and drift key", "1 hp DC, variable speed, water resistant motor", "0 to 1850 rpm", "Runs quietly", "Stainless steel shaft", "NEMA 4X control box", "5 foot power cord", "Constructed of solid, aircraft quality, billet aluminum", "4 mounting holes in its base", "FREE Shipping!"]', included = '["1\\" spindle and drift key"]', specs = '{"Motor": "1 hp DC variable speed", "Speed range": "0-1850 rpm", "Reach": "12\\""}', warranty = NULL WHERE id = 'covington-professional-glass-lathe';
UPDATE products SET blurb = 'The Covington 30 Inch Slab Saw is a heavy welded-steel slab saw with a six-speed power feed and an automatic shut-off at the end of the cut.

The frame is welded separately from the chassis so it will not warp, a quick-return system lets you move the carriage by hand to any position, and an over-running clutch adjusts the feed from soft to hard rock on its own. The tank holds 22 gallons of coolant, the saw runs on 220V/60Hz and weighs 675 lb. A vise, motor and Covington\'s best diamond blade are included.', features = '["Powder coated, heavy welded, steel chassis", "Separately welded frame eliminates warping", "Six-speed power feed with automatic shut-off", "Quick return system allows carriage to be manually returned to any position", "Over-running clutch automatically adjusts from soft to hard rock", "Cross feed permits 8\\" of material to be slabbed", "One piece arbor and flange mounted in housing", "Heavy-duty ball bearings, neoprene sealed, and greased for life", "One-piece vise carriage mounted on a solid key stock with channel guide", "Takes 22 gallons of coolant", "220V, 60Hz", "Made in USA", "FREE Shipping"]', included = '["Vise", "Motor", "Covington\'s Best Diamond Blade"]', specs = '{"Weight": "675 lb", "Power": "220V, 60Hz", "Coolant capacity": "22 gallons"}', warranty = NULL WHERE id = 'covington-30-inch-slab-saw';
