-- Batch 42 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'The Covington 8" Standard Maxi Lap is a flat lap with a cast aluminum body and a 1/3 hp motor with a carrying handle, turning the heads at 1410 rpm.

Three quick-change aluminum heads (no center hole) come with hard or soft rubber. The water manifold and drain kit are included, and the work area is open. It also includes two 8 in silicon carbide sanding discs. Manufacturer\'s warranty applies.', features = '["Cast aluminum body", "3 quick-change aluminum heads (no hole) with hard or soft rubber", "1/3 hp heavy duty motor with carrying handle", "Aluminum heads turn at 1410 rpm", "Water manifold assembly", "Drain kit included", "Unobstructed access to work surface", "Compact and portable design", "Made in USA"]', included = '["Three quick-change aluminum heads with hard or soft rubber", "Two 8\\" silicon carbide sanding discs (100 & 400 grit)", "One 8\\" felt polishing disc", "Water manifold assembly", "Drain kit", "Instructions", "1/3 hp motor (ships separately)"]', specs = '{"Rotation speed": "1410 rpm", "Motor": "1/3 hp", "Disc size": "8\\""}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-8-standard-maxi-lap-flat-lap-machine';
UPDATE products SET blurb = 'The Covington 8" Standard Diamond Maxi Lap is a flat lap that ships with two 8 in resin-bonded diamond sanding discs (220 and 1200 grit) and an 8 in felt polishing disc, 1/8 in thick.

A cast aluminum body holds a 1/3 hp motor with carrying handle, turning quick-change heads with hard or soft rubber at 1410 rpm. A water manifold, drain kit and instructions are included. Manufacturer\'s warranty applies.', features = '["Two 8\\" resin-bonded diamond sanding discs (220 & 1200 grit)", "One 8\\" felt polishing disc (1/8\\" thick)", "1/3 hp heavy duty motor with carrying handle", "Quick-change aluminum heads with hard or soft rubber", "Cast aluminum body", "Water manifold assembly and drain kit included", "1410 rpm operation", "Unobstructed work surface access", "Instructions included"]', included = '["Water manifold assembly", "Drain kit", "Instructions"]', specs = '{"Rotation speed": "1410 rpm", "Motor": "1/3 hp"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-8-standard-diamond-maxi-lap-flat-lap-machine';
UPDATE products SET blurb = 'The Covington 8" Two-Station Expandable Drum Unit has two 8 x 3 in expandable drums driven by a 1/2 hp motor.

The pans and hoods are powder-coated cast aluminum, the base is an aluminum-topped Lam-I-Cushion and the bearings are sealed. It comes with 100 and 220 grit sanding belts and instructions, is made in the USA and carries the manufacturer\'s warranty.', features = '["Powder coated cast aluminum pans and hoods for corrosion resistance", "Two 8\\" x 3\\" expandable drums", "Mounted on an aluminum-topped Lam-I-Cushion base", "1/2 hp motor", "Sealed ball bearings", "Made in USA"]', included = '["Two 8\\" x 3\\" expandable drums", "Two 3\\" x 25-7/32\\" sand belts (100 grit and 220 grit)", "Instructions"]', specs = '{}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-8-two-station-expandable-drum-unit';
UPDATE products SET blurb = 'The Covington 10" Trim Saw With Power Feed feeds the rock into the blade automatically.

A cross feed lets you slab up to 3-1/2 in of material without reclamping, a bulldog vise grips any rock shape and swings away for hand trimming, and a hold-down hook stops the workpiece climbing the blade. It needs about 1/2 gallon of coolant. A motor, operating instructions and the product guarantee are included.', features = '["Power feed feeds rock to saw automatically", "Cross feed permits 3-1/2\\" of material to be slabbed without reclamping", "Bulldog vise grip holds all rock shapes and swings away for hand trimming", "Hold-down hook prevents workpiece from climbing blade or jamming", "1/3 hp motor mounts directly on back of tank casting", "Front shield protects operator from cutting waste", "5/8\\" steel arbor shaft", "Covington Gold Series blade", "Made in USA"]', included = '["Motor", "Operating instructions", "Product guarantee"]', specs = '{"Coolant needed": "1/2 gallon"}', warranty = 'Product guarantee' WHERE id = 'covington-10-trim-saw-with-power-feed';
UPDATE products SET blurb = 'The Gemini Revolution XT Sliding Tray Table is a precision cutting table for the Revolution XT ring saw.

Two adjustment screws square up the cut, magnetic stops set 45-degree angles on or off center, and a double-sided rule is marked in 1/16 in increments. Gemini compares the accuracy to that of a milling machine.', features = '["Precision cutting accuracy comparable to milling machines", "Easy square cut capability via two-screw adjustment", "Magnetic stops for 45-degree angle cuts (on and off center)", "Double-sided measurement rule with 1/16\\" increments", "Blade kerf pre-calculated for accurate measurements"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'gemini-revolution-xt-sliding-tray-table';
UPDATE products SET blurb = 'The Crystalite Turbine Wheel has a saw-toothed profile for fast roughing.

It comes in 6 in and 8 in sizes in 40 and 100 mesh, runs at 1500 to 2000 rpm, and has a 1 in arbor hole with a bushing included.', features = '["Saw-toothed profile", "Fast roughing capability", "1\\" arbor hole", "Bushing included"]', included = '[]', specs = '{"Sizes": "6\\", 8\\"", "Grits": "40, 100 mesh", "Operating speed": "1500-2000 rpm"}', warranty = NULL WHERE id = 'crystalite-turbine-wheel-diamond-grinding-wheel';
UPDATE products SET blurb = 'Crystalite Solid Steel Lap Disks are absolutely flat steel discs with a corrosion-resistant copper undercoat and a 1/2 in arbor hole.

Sizes are 6 and 8 in, in 60, 100, 180, 260, 360, 600, 1200 and 3000 grit.', features = '["Absolutely flat", "Corrosion-resistant copper undercoating", "1/2\\" arbor hole"]', included = '[]', specs = '{"Sizes": "6\\", 8\\"", "Grits": "60, 100, 180, 260, 360, 600, 1200, 3000"}', warranty = NULL WHERE id = 'crystalite-solid-steel-lap-disks';
UPDATE products SET blurb = 'Crystalite Spherical Miracle Radiused Grinding Wheels cut with a double-bite action that removes punting marks.

They suit lapidary work and light glass applications. The arbor hole is 1 in, with bushings for 3/4, 5/8 and 1/2 in, and the radius is 3.0945 in ±0.015.', features = '["Double bite cutting mechanism", "Removes punting marks", "Suitable for lapidary and light glass applications"]', included = '[]', specs = '{"Arbor hole": "1\\" with bushings for 3/4\\", 5/8\\", 1/2\\"", "Radius": "3.0945\\" +/-0.015\\"", "Sizes": "6\\", 8\\"", "Grits": "100, 360, 600 mesh"}', warranty = NULL WHERE id = 'crystalite-spherical-miracle-radiused-grinding-wheels';
UPDATE products SET blurb = 'The Crystalite Ripple Disc is a fast-cutting lap that exposes fresh diamond as its tips wear.

It is well suited to cutting agate, rough cabbing and preforming large faceted stones. The arbor hole is 1/2 in.', features = '["Fast cutting, exposes fresh diamond as tips wear", "Good for agate cutting", "Suited to rough cabbing and preforming large faceted stones", "1/2\\" arbor hole"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'crystalite-ripple-disc-cutting-lap-disk';
UPDATE products SET blurb = 'Gemini Apollo Ring Saw Blade Cartridges let you remove and install blades quickly.

Options include sintered, rigid ring and wired cartridges, and the wired cartridge is compatible with Taurus 3 blades.', features = '["Quick and easy blade removal and installation", "Sintered, rigid ring, and wired cartridge options", "Compatible with Taurus 3 blades (wired cartridge)"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'gemini-apollo-ring-saw-blade-cartridges';
