-- Batch 4 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'The Stand for Covington Combo Trim & Slab Saws is a heavy-duty stand with adjustable legs that levels and squares the saw on any kind of flooring.', features = '["Heavy duty", "Adjustable legs", "Levels and squares saw on any flooring"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'stand-for-covington-combo-trim-slab-saws';
UPDATE products SET blurb = 'Ameritool Diamond Compound is a highly concentrated diamond polishing paste supplied in 5 gram syringes for precise application.

It comes in eight grades: 325, 600, 1200, 3000, 8000, 14K, 50K and 100K mesh. Covington Extender Fluid is the recommended partner.', features = '["Highly concentrated polishing paste", "5-gram syringes for precise application", "Multiple mesh sizes: 325, 600, 1200, 3000, 8000, 14K, 50K, 100K", "Pairs well with Covington Extender Fluid"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'ameritool-diamond-compound';
UPDATE products SET blurb = 'Cerium Oxide Resin-Bonded Flexwheels are polishing wheels with cerium oxide built into the resin, so there is no slurry to mix or clean up.

They are used wet, resist heat deformation, and are rated to a maximum of 1725 rpm. Two sizes are offered, 1.5 x 6 in and 2 x 8 in. The bore is 1 in, with a telescopic bushing and adapters for 3/4 in, 5/8 in and 1/2 in arbors included.', features = '["Use wet", "Highest concentration of Cerium Oxide Compound", "Eliminates wasteful slurry", "No clean-up or filtration needed", "Heat friction deformation-resistant", "1\\" bore standard, bushings for 3/4\\", 5/8\\" and 1/2\\" included", "Maximum RPM 1725"]', included = '["1\\" telescopic bushing with adapters for 3/4\\", 5/8\\", and 1/2\\" arbor sizes"]', specs = '{"Sizes available": "1.5\\" x 6\\", 2\\" x 8\\"", "Max RPM": "1725"}', warranty = NULL WHERE id = 'cerium-oxide-resin-bonded-flexwheels';
UPDATE products SET blurb = 'Covington Vibra Lap Vibrating Lap Bumper Rings are replacement bumper rings for automatic vibrating laps, in 10 in, 12 in and 16 in sizes.', features = '["10\\" size", "12\\" size", "16\\" size"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'covington-vibra-lap-vibrating-lap-bumper-rings';
UPDATE products SET blurb = 'Cerium Oxide Resin-Bonded Belts are wet-use polishing belts with cerium oxide compound bonded into the belt itself, which removes the slurry and shortens cleanup.

They hold their shape without stretching or heat distortion and work on glass, gemstones and other materials. Sizes run from 1.5 x 6 in up to 4 x 106 in.', features = '["Highest concentration of Cerium Oxide Compound", "Designed for wet use", "Eliminates wasteful slurry", "Reduces cleanup time", "Resistant to heat friction deformation", "Maintains shape without stretching", "Works with glass, gemstones, and other materials"]', included = '[]', specs = '{"Sizes available": "1.5\\"x6\\", 2.5\\"x6\\", 3\\"x8\\", 3\\"x24\\", 3\\"x41.5\\", 4\\"x106\\""}', warranty = NULL WHERE id = 'cerium-oxide-resin-bonded-belts';
UPDATE products SET blurb = 'Lortone Drive Belts are replacement belts for Lortone 3-A and 33-B tumblers.

They are easy to fit and keep the barrel turning at a steady rate.', features = '["Compatible with Lortone 3-A and 33-B tumblers", "Durable construction for long-lasting use", "Easy to install", "Maintains consistent rotation for precise results"]', included = '[]', specs = '{"Available models": "3A, 33-B"}', warranty = NULL WHERE id = 'lortone-drive-belts';
UPDATE products SET blurb = 'Covington Tumbler V-Belts come in three lengths: 18 in for the 1/12 hp rolling tumblers (models 251-259), 20 in for the Deluxe Tumbler (model 250) and 22 in for the 1/6 hp rolling tumblers (models 252, 253 and 256).', features = '["18\\" belt for 1/12 hp rolling tumblers (models 251-259)", "20\\" belt for Deluxe Tumbler (model 250)", "22\\" belt for 1/6 hp rolling tumblers (models 252, 253, 256)"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'covington-tumbler-v-belts';
UPDATE products SET blurb = 'The Covington Cast Iron Pulley is a cast iron pulley with a 1 in arbor hole, available in 5.6 in or 6.4 in diameter.', features = '["Premium cast iron construction", "Withstands wear and tear", "Two size options"]', included = '[]', specs = '{"Arbor hole": "1\\"", "Diameter": "5.6\\" or 6.4\\""}', warranty = NULL WHERE id = 'covington-cast-iron-pulley';
