-- Batch 13 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'The Tumble-Bee 1 x 2 Rock Tumbler has a single 2 lb rubber barrel.

It has a grooved non-slip belt, a thermal overload protector, shielded moving parts and a lighted switch, all in a rust-proof composite housing that weighs 5 lb. Light oil, an Allen wrench and a manual come in the box.', features = '["Non-slip drive belt with grooved design", "Thermal overload protector", "Lighted on/off power switch", "Shielded moving parts", "Rust-proof composite housing"]', included = '["One 2 lb rubber barrel", "One bottle of lightweight oil", "3/64\\" Allen wrench", "Instruction manual"]', specs = '{"Dimensions": "13\\" L x 6\\" W x 6\\" H", "Weight": "5 lb"}', warranty = NULL WHERE id = 'tumble-bee-1-x-2-rock-tumbler';
UPDATE products SET blurb = 'The Inland WizlingCG Glass Grinder is a compact stained-glass grinder with a 1/22 hp motor producing 16 oz-in of torque.

The kit includes a 3/4 in, 100 grit diamond head with Allen wrench, a coolant sponge, a standard BitSert and a bit splash guard, plus an instruction manual. It has an injection-molded plastic housing, measures 12 x 10 x 7 in, weighs 6-1/2 lb and carries a five-year warranty.', features = '["3/4\\" diameter, 100 grit diamond grinding head with Allen wrench", "Coolant sponge included", "3/4\\" standard BitSert", "Grinder bit splash guard", "16 oz-in torque, 1/22 hp motor", "Injection-molded plastic housing", "10-1/2\\" x 8-1/2\\" reversible work surface", "Lift-off reservoir", "Made in the USA", "5-year warranty"]', included = '["Instruction manual"]', specs = '{"Dimensions": "12\\" L x 10\\" W x 7\\" H", "Weight": "6-1/2 lb"}', warranty = '5-year warranty' WHERE id = 'inland-wizlingcg-glass-grinder';
UPDATE products SET blurb = 'The Inland 3/4 Inch Diamond Grinding Head offers more usable diamond and a longer life than smaller heads, with a larger diameter for faster grinding.

The brass core is made on Swiss precision machinery and checked for trueness (TIR under .0025 in) before diamond is applied. It fits a 0.312 in arbor and is used wet on stone, glass, tile and minerals or dry on plastics and woods. The diamond coating is guaranteed never to peel.', features = '["More usable diamond, extended lifespan", "Larger diameter for faster grinding", "Brass cores on Swiss precision machinery", "Measured for trueness before diamond application", "Wet for stone, glass, tile, minerals; dry for plastics and woods", "Compatible with most American, German, and select Chinese glass grinders"]', included = '[]', specs = '{"Arbor fit": "0.312\\" (7.92mm)", "TIR": "<.0025\\"", "Material": "CDA 360 brass cores", "Diamond surface height": "0.625\\"", "Also known as": "WB-1"}', warranty = 'Diamond coating guaranteed never to peel, free replacement for the life of the diamonds' WHERE id = 'inland-3-4-inch-diamond-grinding-head';
UPDATE products SET blurb = 'The Inland SecondStory Work Surface for Glass Grinders is a raised open-grid surface, 5 in by 4-1/2 in, that holds glass level while you grind.

Keeping the piece flat prevents angled edges and misshapen holes. A coolant reservoir is built in, and the surface snaps on and off. An L-shaped SecondStory coolant sponge and a user guide are included.', features = '["Elevated 5\\" L x 4-1/2\\" W open grid work surface", "Keeps glass level while grinding, preventing angled edges and misshapen holes", "Built-in coolant reservoir", "Easy-on and easy-off"]', included = '["L-shaped SecondStory coolant sponge", "User guide"]', specs = '{"Work surface": "5\\" L x 4-1/2\\" W"}', warranty = NULL WHERE id = 'inland-secondstory-work-surface-for-glass-grinders';
UPDATE products SET blurb = 'The Inland MagnaShield for Glass Grinders is a 10 x 8-3/4 in optical-quality magnifying shield that guards against grinding and sawing debris.

It rinses clean under running water and fits the Wizard IV, WizCG and WizlingCG grinders.', features = '["Optical-quality magnifying surface", "Protects from grinding and sawing debris", "Rinse clean under running water", "Fits Wizard IV, WizCG, WizlingCG grinders"]', included = '[]', specs = '{"Size": "10\\" x 8-3/4\\""}', warranty = NULL WHERE id = 'inland-magnashield-for-glass-grinders';
UPDATE products SET blurb = 'The Inland Face Shield for Glass Grinders is a 10 x 8-3/4 in acrylic shield that protects you from grinding and sawing debris.

It rinses clean under running water and fits the Wizard IV, WizCG and WizlingCG grinders.', features = '["Large 10\\" x 8-3/4\\" size", "Protects from grinding and sawing debris", "Rinse clean under running water", "Fits Wizard IV, WizCG, WizlingCG grinders"]', included = '[]', specs = '{"Dimensions": "10\\" x 8-3/4\\"", "Material": "Acrylic"}', warranty = NULL WHERE id = 'inland-face-shield-for-glass-grinders';
UPDATE products SET blurb = 'The Inland WizCG Glass Grinder has a 1/11 hp motor with 30 oz-in of torque, stepping up from the WizlingCG.

The kit includes both a 3/4 in and a 1/4 in, 100 grit diamond bit with Allen wrenches, two coolant sponges, a standard BitSert and a bit splash guard, plus an instruction manual. It measures 12 x 10 x 7 in, weighs 6-1/2 lb and is covered by a five-year warranty.', features = '["30 oz-in torque, 1/11 hp motor", "3/4\\" diameter, 100 grit diamond grinding head with Allen wrench", "1/4\\" diameter, 100 grit diamond grinding bit with Allen wrench", "2 coolant sponges", "3/4\\" standard BitSert", "Grinder bit splash guard", "Rustproof, impact resistant housing", "10-1/2\\" x 8-1/2\\" reversible work surface", "Lift-off reservoir", "Made in the USA"]', included = '["Instruction manual"]', specs = '{"Dimensions": "12\\" L x 10\\" W x 7\\" H", "Weight": "6-1/2 lb"}', warranty = '5-year warranty' WHERE id = 'inland-wizcg-glass-grinder';
UPDATE products SET blurb = 'The Inland ScoreOne Glass Cutter Head is a brass-bodied replacement head with a carbide cutting wheel for cleaner scores and longer wheel life.

It installs easily and works on all ScoreOne and ScoreOne Plus machines.', features = '["Carbide cutting wheel for better scores and longer life", "Brass body", "Easy to install", "Works on all ScoreOne and ScoreOne Plus machines"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'inland-scoreone-glass-cutter-head';
UPDATE products SET blurb = 'The Inland ScoreOne Glass Cutter holds a 90-degree cutting angle and applies steady scoring pressure, which cuts down on hand and wrist fatigue.

It has a carbide cutting wheel and works on a bench top or on grid work surfaces. The machine comes with a ScoreOne cutter head and an instruction guide, under a one-year warranty.', features = '["Maintains optimum 90-degree cutting angle", "Consistent scoring pressure", "Reduces hand and wrist fatigue", "Includes carbide cutting wheel", "Works on bench top or grid work surfaces"]', included = '["ScoreOne glass cutter machine with ScoreOne Cutter Head", "Instruction guide"]', specs = '{}', warranty = '1-year warranty' WHERE id = 'inland-scoreone-glass-cutter';
UPDATE products SET blurb = 'The Inland BladeSert Bandsaw Blade Guide supports the blade at the point of the cut, keeping it tracking straight and extending blade life.

It works with diamond, wood and metal blades on the Inland Craft DB-100 band saw.', features = '["Supports blade at the point of sawing", "Keeps blade tracking straight and true", "Prolongs blade life", "Works with diamond, wood and metal blades", "For Inland Craft DB-100 band saws"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'inland-bladesert-bandsaw-blade-guide';
