-- Batch 24 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'The Covington Super Diamond Lapidary Maxi Lap is a compact, portable flat lap with a cast aluminum body and a 1/3 hp motor with a carrying handle.

Quick-change aluminum heads without a center hole make it fast to switch stages, and a water manifold, pump and tubing are set up for you. The package includes a perforated diamond disc system (coarse, medium and fine), a 1200 grit diamond disc and a leather polishing disc.', features = '["Cast aluminum body", "1/3 hp motor with carrying handle", "Quick-change aluminum heads (no hole)", "Water manifold assembly, pump, tubing", "Compact and portable"]', included = '["Perforated diamond disc system (coarse, medium, fine)", "1200 grit diamond disc", "Leather polishing disc", "Drain kit", "Book about using diamond abrasives", "Instructions"]', specs = '{}', warranty = NULL WHERE id = 'covington-super-diamond-lapidary-maxi-lap-flat-lap-machine';
UPDATE products SET blurb = 'The Covington 8 Inch Perfect Diamond Lapidary Maxi Lap is a quiet, portable flat lap running at 1410 rpm on a 1/3 hp motor with a carrying handle.

The body is heavy-duty cast aluminum with quick-change aluminum heads (no center hole), and a water manifold and pump are included. It comes with an aluminum head with steel disc plus nickel-bond discs starting at 100 and 260 grit. Manufacturer\'s warranty applies.', features = '["Heavy duty cast aluminum body", "Quick-change aluminum heads (no hole)", "Water manifold and pump", "1/3 hp motor with carrying handle", "Runs quietly at 1410 rpm", "Compact and portable"]', included = '["One aluminum head with steel disc", "100 grit nickel bond disc", "260 grit nickel bond disc", "325 grit resin bond disc", "600 grit resin bond disc", "1200 grit resin bond disc", "Synthetic felt disc"]', specs = '{"Motor": "1/3 hp", "Speed": "1410 rpm"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-8-inch-perfect-diamond-lapidary-maxi-lap';
UPDATE products SET blurb = 'The Covington Perfect Diamond Glass Maxi Lap is a portable flat lap for glass, available in 8 in and 10 in sizes.

A 1/3 hp motor turns the heads at 1410 rpm in a heavy-duty cast aluminum tank, with a water manifold and pump. Discs include 100 and 260 grit nickel bond and a 325 grit resin bond. Manufacturer\'s warranty applies.', features = '["Quick-change aluminum heads (no hole)", "Heavy duty cast aluminum tank", "Water manifold and pump", "1/3 hp motor with carrying handle", "1410 rpm head rotation", "Compact and portable"]', included = '["One 100 grit nickel bond disc", "One 260 grit nickel bond disc", "One 325 grit resin bond disc", "One synthetic felt disc"]', specs = '{"Sizes": "8\\", 10\\"", "Motor": "1/3 hp", "Speed": "1410 rpm"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-perfect-diamond-glass-maxi-lap';
UPDATE products SET blurb = 'The Covington Super Diamond Glass Maxi Lap is a cast aluminum flat lap with a 1/3 hp motor and carrying handle, set up for glass.

It comes with a perforated diamond disc system, a cork pre-polishing disc, a felt polishing disc and 1 lb of 2-F pumice. Quick-change heads without a center hole, and a water manifold, pump and tubing round out the package. Manufacturer\'s warranty applies.', features = '["Cast aluminum body", "Cork pre-polishing disc", "1 lb of 2-F pumice", "Felt polishing disc", "Water manifold assembly, pump, tubing", "1/3 hp motor with carrying handle", "Quick-change aluminum heads (no hole)"]', included = '["Cork pre-polishing disc", "1 lb of 2-F pumice", "Felt polishing disc", "Perforated diamond disc system (coarse, medium, fine)", "Drain kit", "Book about using diamond abrasives", "Instructions"]', specs = '{}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-super-diamond-glass-maxi-lap-flat-lap-machine';
UPDATE products SET blurb = 'The Covington Variable Speed Grinder Polisher has a 1/2 hp high-torque motor with speed control from 800 to 1725 rpm.

The arbor is powder-coated cast aluminum on a 1 x 18 in shaft with neoprene-sealed ball bearings greased for life, and it stands on an aluminum-topped Lam-I-Cushion base. Flanges, nuts, drive pulley, belt guard, water valves and drains are included. Manufacturer\'s warranty applies.', features = '["1\\" x 18\\" shaft", "1/2 hp high torque motor", "Neoprene sealed ball bearings, greased for life", "Speed control 800-1725 rpm", "Powder coated cast aluminum arbor", "Aluminum-topped Lam-I-Cushion base"]', included = '["Flanges", "Nuts", "Drive pulley", "Belt guard", "Water valves and drains"]', specs = '{"Speed range": "800-1725 rpm"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-variable-speed-grinder-polisher';
UPDATE products SET blurb = 'The Covington Two Station Open Arbor is a build-your-own grinder/polisher with a heavy-duty cast aluminum arbor and a V-belt drive.

The shaft is 1 x 23-3/4 in, turned, ground and polished, and runs in neoprene-sealed ball bearings greased for life. A 3 in drive pulley, two sets of 3 in aluminum flanges, two nuts and the V-belt come with it, and a 2 in riser shim is optional.', features = '["Build-your-own style grinder/polisher", "Heavy duty cast aluminum construction", "Fully customizable", "1\\" x 23-3/4\\" turned ground and polished shaft", "V-belt system", "Neoprene sealed ball bearings, greased for life", "Optional 2\\" riser shim"]', included = '["Two nuts", "3-inch drive pulley", "Two sets of 3-inch aluminum flanges", "V-belt"]', specs = '{}', warranty = NULL WHERE id = 'covington-two-station-open-arbor';
UPDATE products SET blurb = 'The Covington 4 Station Expandable Drum Unit has four 8 x 3 in expandable drums loaded with sanding belts in 100, 220, 400 and 600 grit.

Speed is variable from 800 to 1725 rpm. The arbor is powder-coated cast aluminum with drain plugs, the bearings are neoprene-sealed and greased for life, and a belt guard with instructions is included. Manufacturer\'s warranty applies.', features = '["Four 8\\" x 3\\" expandable drums", "Four sanding belts (100, 220, 400, 600 grit)", "Belt guard with instructions", "Neoprene sealed ball bearings, greased for life", "Powder-coated cast aluminum arbor with drain plugs", "Variable speed 800-1725 rpm", "1/2 hp high-torque motor", "Rustproof aluminum-topped base"]', included = '["Four 3\\" x 8\\" sanding belts (100, 220, 400, 600 grit)"]', specs = '{"Speed range": "800-1725 rpm"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-4-station-expandable-drum-unit';
UPDATE products SET blurb = 'Covington Cabinet Stands are powder-coated sheet metal stands in small and large sizes.

A door kit and table top are optional.', features = '["Powder coated sheet metal", "Small or large size", "Optional door kit and table top"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'covington-cabinet-stands';
UPDATE products SET blurb = 'The Covington Diamond T-Bar Dressing Tool trues silicon carbide wheels.', features = '["Trues silicon carbide wheels"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'covington-diamond-t-bar-dressing-tool';
UPDATE products SET blurb = 'Covington Pliers are European-made lap-joint pliers in chain nose, round nose and flat nose versions.', features = '["European quality", "Lap-joint construction", "Chain Nose, Round Nose, and Flat Nose variants"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'covington-pliers';
