-- Batch 34 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'The Covington Mounted Wet Belt Sander takes 3 x 24 in belts with a quick-change belt system and gives you 6 in of workspace.

It has a 1/3 hp motor, belt guard, water valve with spray nozzle and an adjustable back plate. The finish is powder-coated, the bearings double-sealed and shielded, and it measures 24 x 12 x 20 in and weighs 45 lb. Instructions and manufacturer\'s warranty are included.', features = '["Uses 3\\" x 24\\" sanding belts", "1/3 hp motor", "Belt guard", "Water valve and spray nozzle", "Quick change belt system", "Powder coated for durability", "Double sealed and shielded bearings", "6\\" of workspace", "Adjustable back plate", "Rustproof aluminum topped Lam-I-Cushion base"]', included = '["Instructions", "Manufacturer\'s warranty"]', specs = '{"Weight": "45 lb", "Width": "24\\"", "Height": "20\\"", "Depth": "12\\""}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-mounted-wet-belt-sander';
UPDATE products SET blurb = 'The Covington Horizontal Wet Belt Sander is built on a heavy 16-gauge steel tank with an unobstructed work area and quick-change belts.

Belt tracking adjusts with a single control, the hood, base and bearing support are powder-coated, and the bearings are shielded, double-sealed and greased for life. It measures 24 x 12 x 10 in and weighs 43 lb.', features = '["Heavy 16-gauge steel tank", "Unobstructed access to work area", "Quick change belt system", "Powder coated hood, base, and bearing support", "Single control alignment", "Shielded bearings, double sealed and greased for life", "Adjustable 3\\" x 6\\" back plate", "Water valve and spray nozzle", "Uses 3\\" x 25-7/32\\" sanding belts", "1/3 hp motor", "Rustproof aluminum-topped Lam-I-Cushion base", "Instructions included"]', included = '["Instructions"]', specs = '{"Weight": "43 lb", "Width": "24\\"", "Height": "10\\"", "Depth": "12\\""}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-horizontal-wet-belt-sander';
UPDATE products SET blurb = 'The Covington Deluxe Commercial Wet Belt Sander runs 3 x 41-1/2 in belts on an upright bearing-support casting mounted to a cast aluminum tank.

The work area is open, belts change quickly and tracking adjusts with a single control. It includes a push-to-connect water valve and instructions. It measures 27 x 27 x 14 in and weighs 67 lb.', features = '["Uses 3\\" x 41-1/2\\" sanding belts", "Upright bearing support casting on cast aluminum tank", "Unobstructed access to work area", "Quick change belt system", "Powder coated hood, base, and bearing support", "Single control alignment for belt tracking", "1/2 hp motor", "Belt guard", "Shielded bearings, double sealed and greased for life", "Adjustable back plate for flat surface sanding", "Push-to-connect water valve", "Instructions included"]', included = '["Push-to-connect water valve", "Instructions"]', specs = '{"Weight": "67 lb", "Width": "27\\"", "Height": "14\\"", "Depth": "27\\""}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-deluxe-commercial-wet-belt-sander';
UPDATE products SET blurb = 'The Covington Commercial Horizontal Wet Belt Sander sits on a heavy 16-gauge steel tank and gives you unobstructed access to the work.

A single control keeps the belt tracking true, belts change quickly, and the bearings are shielded, double-sealed and greased for life. The hood, base and bearing support are powder-coated. It measures 25 x 25 x 12 in and weighs 70 lb.', features = '["Heavy 16-gauge steel tank", "Unobstructed access to work area", "Quick change belt system", "Powder coated hood, base, and bearing support", "Single control alignment to keep belt running true", "Shielded bearings, double sealed and greased for life", "Adjustable back plate, 3\\" x 13\\" working space"]', included = '[]', specs = '{"Weight": "70 lb", "Width": "25\\"", "Height": "12\\"", "Depth": "25\\""}', warranty = NULL WHERE id = 'covington-commercial-horizontal-wet-belt-sander';
UPDATE products SET blurb = 'The Covington Commercial Wet Belt Sander takes 3 x 41-1/2 in belts, with an upright bearing-support casting on a cast aluminum tank.

It has a built-in water valve and spray nozzle, an open work area, quick-change belts and a powder-coated hood, base and bearing support. It measures 27 x 27 x 14 in and comes with instructions and the manufacturer\'s warranty.', features = '["Uses 3\\" x 41-1/2\\" sand belts", "Unobstructed access to work area", "Quick change belt system", "Upright bearing support casting on cast aluminum tank", "Built in water valve and spray nozzle", "Powder coated hood, base, and bearing support", "Single control alignment", "1/3 hp motor", "Belt guard", "Shielded bearings, double sealed and greased for life", "Adjustable 4\\" high back plate", "Rustproof aluminum topped Lam-I-Cushion base", "Instructions included"]', included = '["Instructions"]', specs = '{"Width": "27\\"", "Height": "14\\"", "Depth": "27\\""}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-commercial-wet-belt-sander';
UPDATE products SET blurb = 'Gemini Revolution XT Replacement Red Cone Grommets are sold as a pair. They support the sides of the blade on the Gemini Revolution XT saw.', features = '["One pair", "Red", "Supports sides of blade", "Fits Gemini Revolution XT saw"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'gemini-revolution-xt-replacement-red-cone-grommets';
UPDATE products SET blurb = 'The Covington Submersible Pump and Tank is a self-contained coolant system with a 110V pump, a grounded 3-prong cord, 10 ft of 1/2 in vinyl tubing and wheels.

The pump moves 200 GPH at 1 ft and 105 GPH at 5 ft. The tank holds about 17.5 gallons and has two graduated dividers to settle out sediment.', features = '["Self-contained pump system", "110V pump", "3-prong grounded plug and cord", "10\' of 1/2\\" vinyl tubing", "200 GPH at 1 foot", "105 GPH at 5 feet", "2 graduated dividers to separate sediment", "Wheels included"]', included = '["10\' of 1/2\\" vinyl tubing", "Wheels"]', specs = '{"Tank capacity": "approximately 17.5 gallons", "Tank dimensions": "approximately 30\\" x 18\\" x 12\\"", "Pump output": "200 GPH at 1 ft, 105 GPH at 5 ft"}', warranty = NULL WHERE id = 'covington-submersible-pump-and-tank';
UPDATE products SET blurb = 'Covington Sintered Diamond Cutter Cups for Sphere Machines are 4 in cups for making spheres from 3-3/4 in to 6-1/2 in across.

The thread is 3/4 in national pipe thread.', features = '["4\\" in diameter", "For 3-3/4\\" to 6-1/2\\" spheres", "3/4\\" national pipe thread"]', included = '[]', specs = '{"Diameter": "4\\"", "Sphere size range": "3-3/4\\" to 6-1/2\\"", "Thread": "3/4\\" NPT"}', warranty = NULL WHERE id = 'covington-sintered-diamond-cutter-cups-for-sphere-machines';
UPDATE products SET blurb = 'Covington Magnetic Dot Lap Discs have nickel-plated diamond rings on a magnet-backed disc that changes fast.

Sizes are 12, 18 and 24 in, in 100, 260, 360 and 600 grit, with a 1 in arbor hole.', features = '["Nickel plated diamond rings", "Magnetic backed", "Super-fast to change", "1\\" arbor hole"]', included = '[]', specs = '{"Sizes": "12\\", 18\\", 24\\"", "Grits": "100, 260, 360, 600", "Arbor hole": "1\\""}', warranty = NULL WHERE id = 'covington-magnetic-dot-lap-discs';
UPDATE products SET blurb = 'Covington Gold Series Diamond Saw Blades have more diamond in the notched rim and a stiffer core for faster cutting and longer life.

They work well on agate, geodes and petrified wood. The 6 in and 8 in sizes have a .044 in rim and the 10 in has .052 in, for 1/2 to 5/8 in arbors.', features = '["More diamonds in notched rim", "Stiffer core for faster cutting and longer life", "Works well on agates, geodes, and petrified wood"]', included = '[]', specs = '{"6\\"": "0.044\\" rim, 1/2\\"-5/8\\" arbor", "8\\"": "0.044\\" rim, 1/2\\"-5/8\\" arbor", "10\\"": "0.052\\" rim, 1/2\\"-5/8\\" arbor", "16\\"": "0.094\\" rim, 5/8\\"-3/4\\"-1\\" arbor"}', warranty = NULL WHERE id = 'covington-gold-series-diamond-saw-blades';
