-- Batch 33 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'Covington Nickel Bond Magnetic Discs are magnet-backed diamond discs that change quickly, in 12, 18 and 24 in diameters.

Grits are 45, 60, 80, 100, 140, 200, 270, 325 and 500. The arbor hole is 1 in, or 1/4 in on the 12 in disc if requested.', features = '["Magnetic backed", "Fast to change", "1\\" arbor hole (1/4\\" available for 12\\" discs)"]', included = '[]', specs = '{"Sizes": "12\\", 18\\", 24\\"", "Grits": "45, 60, 80, 100, 140, 200, 270, 325, 500"}', warranty = NULL WHERE id = 'covington-nickel-bond-magnetic-discs';
UPDATE products SET blurb = 'The Covington Diamond Radius Grinding Wheel is a nickel-plated wheel with a steel rim and a 1-3/16 in plastic hub, with a rounded edge profile.

Sizes are 6 x 1-1/2 in and 8 x 1-1/2 in, in 100, 180, 360 and 600 grit. The arbor is 1 in with a bushing included for 1/2, 5/8 or 3/4 in shafts.', features = '["Nickel-plated", "Steel-rimmed", "1-3/16\\" wide plastic hub", "1\\" arbor hole", "Bushing for 1/2\\", 5/8\\" or 3/4\\" arbor included"]', included = '["Bushing for arbor size compatibility"]', specs = '{"Sizes": "6\\" x 1-1/2\\" or 8\\" x 1-1/2\\"", "Grits": "100, 180, 360, 600", "Arbor hole": "1\\""}', warranty = NULL WHERE id = 'covington-diamond-radius-grinding-wheel';
UPDATE products SET blurb = 'The Silicon Carbide Grinding Wheel, 6 inch, is a 220 grit wheel, 1 in wide.', features = '["6 inch size", "220 grit", "1 inch width"]', included = '[]', specs = '{"Size": "6\\"", "Width": "1\\"", "Grit": "220"}', warranty = NULL WHERE id = 'silicon-carbide-grinding-wheel-6-inch-1-inch-220';
UPDATE products SET blurb = 'The Silicon Carbide Grinding Wheel, 8 inch, is a 220 grit wheel, 5/8 in wide.', features = '["8 inch size", "220 grit", "5/8 inch width"]', included = '[]', specs = '{"Size": "8\\"", "Width": "5/8\\"", "Grit": "220"}', warranty = NULL WHERE id = 'silicon-carbide-grinding-wheel-8-inch-5-8-inch-220';
UPDATE products SET blurb = 'Covington Ultimate Sintered Diamond Wheels are balanced wheels with diamond evenly dispersed through a sintered rim, and more sintering on the rim for longer life.

They are 1.50 in wide in 6 in and 8 in diameters and come in 30/35, 140/170, 200/230, 400/500 and 600/800 grits.', features = '["Long lasting", "Higher diamond concentration in sintered rim", "Balanced", "Diamond evenly dispersed", "More sintering on rim", "1.50\\" width"]', included = '[]', specs = '{"Sizes": "6\\", 8\\"", "Grits": "30/35, 140/170, 200/230, 400/500, 600/800", "Width": "1.50\\""}', warranty = NULL WHERE id = 'covington-ultimate-sintered-diamond-wheels';
UPDATE products SET blurb = 'The Silicon Carbide Grinding Wheel, 10 inch, comes in 3/4 in or 1-1/2 in widths and in 100 or 220 grit.', features = '["10 inch size", "Available in 3/4\\" and 1-1/2\\" widths", "100 and 220 grit options"]', included = '[]', specs = '{"Size": "10\\"", "Widths": "3/4\\", 1-1/2\\"", "Grits": "100, 220"}', warranty = NULL WHERE id = 'silicon-carbide-grinding-wheel-10-inch';
UPDATE products SET blurb = 'The Covington Trim Saw for Glass mounts a 1/3 hp motor directly on the back of the tank casting and has an adjustable blade guard for different material sizes.

The tank, table top and blade guard are powder-coated, and the bearings are neoprene-sealed and greased for life. It measures 28 x 18 x 15 in, weighs 56 lb and comes with instructions and the manufacturer\'s warranty.', features = '["Adjustable blade guard for various material sizes", "Neoprene sealed ball bearings, greased for life", "Powder coated tank, table top, and blade guard", "1/3 hp motor mounts directly on back of tank casting", "Choice of 10\\" Ultimate Glass Blade or Platinum Resin Blade", "Power feed available", "Koolerant Kontrol valve", "Twin drains", "Aluminum-topped Lam-I-Cushion base", "Instructions included", "Manufacturer\'s warranty"]', included = '["Instructions"]', specs = '{"Weight": "56 lb", "Width": "28\\"", "Height": "15\\"", "Depth": "18\\""}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-trim-saw-for-glass';
UPDATE products SET blurb = 'The Covington Trim Saw Vise opens to 1-5/8 in and grips rock firmly.

It fits Covington models 494, 495 and 497.', features = '["Compatible with Covington models #494, #495, and #497", "Opens to 1-5/8\\"", "Firmly grips rock"]', included = '[]', specs = '{"Opening capacity": "1-5/8\\""}', warranty = NULL WHERE id = 'covington-trim-saw-vise';
UPDATE products SET blurb = 'The Covington 6 Inch Trim Saw has a 1/3 hp motor, a heavy-duty cast aluminum tank with powder coating and shielded, double-sealed bearings greased for life.

Blade and belt guards are fitted, it runs quietly, and a 6 in Gold Series blade is included with instructions. It measures 24 x 12 x 10 in and weighs 39 lb. One-year manufacturer\'s warranty.', features = '["Heavy duty cast aluminum tank construction", "Powder coated tank for long life", "Shielded bearings, double sealed and greased for life", "Blade guard and belt guard for safety", "6\\" Gold Blade included", "1/3 hp motor", "Runs quietly", "Lam-I-Cushion base", "Instructions included", "1 Year Manufacturer\'s Warranty"]', included = '["6\\" Gold Series blade", "Instructions"]', specs = '{"Weight": "39 lb", "Width": "24\\"", "Height": "10\\"", "Depth": "12\\""}', warranty = '1 Year Manufacturer\'s Warranty' WHERE id = 'covington-6-inch-trim-saw';
UPDATE products SET blurb = 'Covington Wet Belt Sander Stands are powder-coated heavy-gauge box tubing stands, 32 in tall.

A 12 x 24 in stand fits models 460, 466, 760 and 761, and a 22 x 24 in stand fits model 762.', features = '["Heavy gauge box tubing", "Powder coated", "32\\" tall"]', included = '[]', specs = '{"Sizes": "12\\" x 24\\" (fits #460, 466, 760, 761), 22\\" x 24\\" (fits #762)", "Height": "32\\""}', warranty = NULL WHERE id = 'covington-wet-belt-sander-stands';
