-- Batch 41 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'The Covington 8 Inch Deluxe Diamond Combo Unit combines a saw and grinder on five workstations, with two drive motors and a Levermatic speed control that changes in 8 rpm steps.

The grinding side uses a 1/3 hp high-torque motor and has an adjustable cab and wheel rest. Castings, hood and belt guard are powder-coated aluminum. It includes two 8 x 1-1/2 in metal-bond diamond wheels (100 and 220 grit) and an 8 in lever lock drum, and is covered by the product guarantee.', features = '["Five workstations", "Adjustable cab and wheel rest", "1/3 hp heavy duty, high torque motor", "Levermatic speed control with 8 rpm-changes", "Powder coated aluminum castings, hood, and belt guard resist corrosion", "Two drive motors for saw and grinder", "10\\" trim saw with Covington Gold Series diamond blade"]', included = '["Two 8\\" x 1-1/2\\" metal bonded diamond grinding wheels (100 & 220 grit)", "One 8\\" lever lock drum with silicon carbide sand cloth (400 grit)", "One 8\\" x 1\\"-14RH aluminum head with diamond disc (1200 grit)", "One 8\\" x 1\\"-14RH aluminum head with leather disc", "5-gram syringe of 50,000 mesh diamond compound", "2-ounce bottle of extender fluid", "Book about using diamond abrasives", "Sample kit with Koolerant, polish powder, brush, dop sticks, and wax", "Instructions"]', specs = '{}', warranty = 'Product guarantee' WHERE id = 'covington-8-inch-deluxe-diamond-combo-unit';
UPDATE products SET blurb = 'The Covington 6 Inch Silicon Carbide Combination Unit puts a saw and grinding wheels on one machine, on a rustproof aluminum-topped Lam-I-Cushion base.

The sealed ball bearings are mounted in rubber for smooth, quiet running, the main shaft is stainless steel, and the castings, hood and belt guard are powder-coated aluminum. It comes with a 6 in Gold Series diamond blade, a slab vise, water valves and drains, and is covered by the product guarantee.', features = '["Sealed ball bearings mounted in rubber for quiet, smooth operation", "Mounted on rustproof aluminum-topped Lam-I-Cushion base", "Stainless steel main shaft resists rust", "Powder coated aluminum castings, hood, and belt guard", "Continuous variable speed control from 800 to 1725 rpm", "Quick change hood and polishing buff", "Adjustable cab and wheel rest", "1/3 hp motor"]', included = '["One 6\\" Covington Gold Series diamond blade", "Slab vise", "Water valves and drains", "Two 6\\" x 1\\" silicon carbide grinding wheels (100 & 220 grit)", "One 6\\" expandable drum", "One 6\\" x 5/8\\"-18RH aluminum head with leather disc", "Sample kit (Koolerant, polish powder, brush, dop sticks, wax)", "Switch cord, belt guard, instructions"]', specs = '{}', warranty = 'Product guarantee' WHERE id = 'covington-6-inch-silicon-carbide-combination-unit';
UPDATE products SET blurb = 'The Covington 6 Inch Diamond Combination Unit puts a saw and diamond grinding wheels on one machine, on a rustproof aluminum-topped Lam-I-Cushion base.

The sealed ball bearings are mounted in rubber for smooth, quiet running, the main shaft is stainless steel, and the castings, hood and belt guard are powder-coated aluminum. It comes with a 6 in Gold Series diamond blade, a slab vise, water valves and drains, plus 6 x 1-1/2 in diamond wheels. Manufacturer\'s warranty applies.', features = '["Sealed ball bearings mounted in rubber for quiet and smooth operation", "Mounted on rustproof aluminum-topped Lam-I-Cushion base", "Stainless steel main shaft resists rust", "Powder coated aluminum castings, hood, and belt guard", "Continuous variable speed control from 800 to 1725 rpm", "Quick change hood and polishing buff", "Adjustable cab and wheel rest", "1/3 hp motor"]', included = '["One 6\\" Covington Gold Series diamond blade", "Slab vise, water valves, drains", "Two 6\\" x 1-1/2\\" metal bonded diamond grinding wheels (100 & 220 grit)", "One 6\\" expandable drum", "One 2-1/2\\" x 18-15/16\\" diamond sanding belt (1200 grit)", "Five 2-1/2\\" x 18-15/16\\" silicon carbide sanding belts (400 grit)", "One 6\\" aluminum head with leather disc", "One 5-gram syringe of 50,000 mesh diamond compound", "One 2-ounce bottle of extender fluid", "Sample kit with Koolerant, polish powder, brush, dop sticks, and wax", "Book about using diamond abrasives", "Instructions"]', specs = '{}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-6-inch-diamond-combination-unit';
UPDATE products SET blurb = 'The Covington Two-Station Closed Arbor is a build-your-own grinder/polisher that accepts 6, 8 and 10 in wheels.

The heavy-duty cast aluminum construction has a fully sealed front casting, a turned, ground and polished shaft and neoprene-sealed ball bearings greased for life. A 3 in drive pulley, V-belt, 3 in flanges and two nuts are included. The base measures 7-1/4 x 7 x 8-1/2 in.', features = '["Build-your-own style grinder/polisher", "Accepts 6\\", 8\\", and 10\\" wheels", "Heavy-duty cast aluminum construction", "Fully sealed front casting", "Turned, ground and polished shaft", "Heavy-duty ball bearings, neoprene sealed and greased for life", "Choice of shaft size"]', included = '["3\\" drive pulley and V-belt", "3\\" flanges", "2 nuts"]', specs = '{"Base": "7-1/4\\" L x 7\\" W x 8-1/2\\" H"}', warranty = NULL WHERE id = 'covington-engineering-two-station-closed-arbor';
UPDATE products SET blurb = 'The Covington Double Half-Gallon Rolling Rock Tumbler runs two solid LLDPE barrels, 12 lb in total.

A fan-cooled 1/12 hp motor turns them on solid 1/2 in steel shafts with DuPont nylon bearings, in a 17 in cast aluminum and steel chassis with a powder-coated frame and belt guard. Instructions and the manufacturer\'s warranty are included.', features = '["Two solid LLDPE barrels", "17\\" cast aluminum and steel chassis", "Heavy duty cast aluminum construction", "Powder coated frame and belt guard", "Solid 1/2\\" steel support shafts", "DuPont nylon bearings", "Fan cooled 1/12 hp motor", "12 lb total capacity", "Instructions included", "Made in the USA"]', included = '["Instructions"]', specs = '{"Capacity": "12 lb total"}', warranty = 'Manufacturer\'s warranty' WHERE id = 'covington-double-half-gallon-rolling-rock-tumbler';
UPDATE products SET blurb = 'The Covington 24 Inch Slab Saw is a 400 lb welded-steel slab saw with a six-speed power feed, automatic shut-off and a quick-return system for repositioning the carriage by hand.

The frame is welded separately from the chassis to prevent warping, and an over-running clutch adapts to soft or hard rock. A vise (12 or 18 in), motor and Covington\'s best diamond blade are included.', features = '["Powder coated, heavy welded steel chassis", "Separately welded frame eliminates warping", "Six-speed power feed with automatic shut-off", "Quick return system for manual carriage positioning", "Over-running clutch automatically adjusts from soft to hard rock", "Cross feed permits 8\\" of material slabbing without reclamping", "One-piece arbor and flange mounted in housing", "Heavy-duty ball bearings, neoprene sealed and greased for life", "One-piece vise carriage on solid key stock with channel guide"]', included = '["Vise", "Motor", "Covington\'s Best Diamond Blade"]', specs = '{"Weight": "400 lb", "Vise sizes": "12\\" or 18\\""}', warranty = NULL WHERE id = 'covington-24-inch-slab-saw';
UPDATE products SET blurb = 'The Covington 20 Inch Slab Saw is a 345 lb welded-steel slab saw with a six-speed power feed, automatic shut-off and quick-return carriage.

The separately welded frame resists warping and an over-running clutch adjusts for soft to hard rock. It needs about 7-1/2 gallons of coolant and comes with a 10 in vise, motor and an A-Series Signature blade.', features = '["Powder-coated, heavy-welded steel construction", "Separately welded frame prevents warping", "Six-speed power feed with automatic shut-off", "Quick return system for manual carriage positioning", "Over-running clutch auto-adjusts for soft to hard rock", "Cross feed permits 8\\" of material to be slabbed without re-clamping", "One-piece 1\\" arbor with flange housing", "Sealed, greased ball bearings", "One-piece vise carriage with solid key stock mounting", "Includes 10\\" vise"]', included = '["Saw", "Vise", "Motor", "Covington\'s A-Series Signature Blade", "10\\" vise"]', specs = '{"Weight": "345 lb", "Coolant needed": "7-1/2 gallons"}', warranty = NULL WHERE id = 'covington-20-inch-slab-saw';
UPDATE products SET blurb = 'The Covington 16 Inch Combination Trim & Slab Saw converts between slab and trim saw modes, using a sawmill-type carriage on steel ways.

The power feed has a 4 in cross feed adjusting 1/16 in per turn, and a rigid vise with steel jaw tongue grips the rock. An A-Series Signature blade is included; the 1/2 hp motor ships separately. It measures 37 x 26 x 29 in and ships at about 200 lb, and a leg stand adds 22 in of height.', features = '["1/2 hp motor (ships separately)", "Sawmill type carriage on steel ways", "Power feed with 4\\" cross feed (1/16\\" per turn adjustments)", "Converts between slab and trim saw modes", "Rigid grip vise with steel jaw tongue", "Includes A-Series Signature Blade"]', included = '["A-Series Signature Blade"]', specs = '{"Dimensions": "37\\" L x 26\\" W x 29\\" H (leg stand adds 22\\")", "Shipped weight": "approx. 200 lb (basic), approx. 225 lb (with legs)", "Coolant needed": "3 gallons"}', warranty = NULL WHERE id = 'covington-16-inch-combination-trim-slab-saw';
UPDATE products SET blurb = 'The Covington 14 Inch Combination Trim & Slab Saw is light enough to move but sturdy enough for regular use, and converts from slab saw to trim saw with a drop-in table.

A sawmill-type carriage glides on steel ways with a 4 in cross feed that adjusts 1/16 in per turn for even slabs. An A-Series Signature blade is included; the 1/2 hp motor ships separately. It measures 37 x 26 x 29 in and weighs 220 lb.', features = '["1/2 hp motor (ships separately)", "Sawmill type carriage gliding on steel ways", "4\\" cross feed adjusts 1/16\\" per turn for uniform slabbing", "Lightweight yet heavy-duty construction", "Easily converts from slab saw to trim saw with drop-in table", "Rigid grip vise with steel jaw tongue for secure, square holding", "Made in the USA"]', included = '["A-Series Signature Blade"]', specs = '{"Dimensions": "37\\" L x 26\\" W x 29\\" H (including motor, leg stand adds 22\\")", "Weight": "220 lb"}', warranty = NULL WHERE id = 'covington-14-inch-combination-trim-slab-saw';
UPDATE products SET blurb = 'The Covington 12 Inch Combination Trim Saw & Slab Saw is light enough to move easily and sturdy enough for everyday use, converting from slab saw to trim saw.

A sawmill-type carriage glides on steel ways with a 4 in cross feed that adjusts 1/16 in per turn for even slabs. An A-Series Signature blade is included; the 1/2 hp motor ships separately. It measures 37 x 26 x 29 in and weighs 220 lb.', features = '["1/2 hp motor, ships separately", "Sawmill type carriage glides on steel ways", "4\\" cross feed adjusts 1/16\\" per turn for uniform slabbing", "Light enough to be moved easily", "Heavy duty enough for everyday use", "Easily converts from slab saw to trim saw with drop-in table", "Rigid grip vise with steel jaw tongue contacting full vise length", "Made in USA"]', included = '["A-Series Signature Blade"]', specs = '{"Dimensions": "37\\" L x 26\\" W x 29\\" H (including motor, leg stand adds 22\\")", "Weight": "220 lb"}', warranty = NULL WHERE id = 'covington-12-inch-combination-trim-saw-slab-saw';
