-- Batch 20 of an ongoing pass over the catalog, with original descriptions written for Bedrock Lapidary.
-- Safe to re-run.

UPDATE products SET blurb = 'Covington Small Sphere Machine Cutter Cups are sold in pairs, or as a set, in 1/4, 5/16, 3/8, 5/8 and 7/8 in sizes.', features = '["Sold in pairs", "Set option available"]', included = '[]', specs = '{"Sizes": "1/4\\", 5/16\\", 3/8\\", 5/8\\", 7/8\\""}', warranty = NULL WHERE id = 'covington-small-sphere-machine-cutter-cups';
UPDATE products SET blurb = 'Covington Cast Iron Cutter Cups are sold as a set of three for three-headed sphere machines.

The soft cast iron embeds grit, which speeds grinding. Sizes are 1, 1-3/8, 2-3/8, 3-3/8 and 4-3/8 in, with either a 1-8 NC or 1-14 NF thread.', features = '["Soft cast-iron construction", "Embeds grit for faster grinding", "For three-headed sphere machines"]', included = '["Set of 3 cutter cups"]', specs = '{"Sizes": "1\\", 1-3/8\\", 2-3/8\\", 3-3/8\\", 4-3/8\\"", "Thread options": "1\\"-8 NC or 1\\"-14 NF"}', warranty = NULL WHERE id = 'covington-cast-iron-cutter-cups-set-of-three';
UPDATE products SET blurb = 'Covington Gem Marking Templates are shape templates, color-coded in blue, gold or red, sold as singles or doubles.

The aluminum versions are rigid and .030 in thick. The plastic versions are clear so you can see the stone through them. Sets with aluminum templates include an aluminum scribe.', features = '["Available in singles or doubles", "Color-coded by shape", "Aluminum: rigid, .030\\" thick", "Plastic: clear for visibility", "Colors: Blue, Gold, Red"]', included = '["Aluminum scribe (with sets)"]', specs = '{"Aluminum thickness": ".030\\""}', warranty = NULL WHERE id = 'covington-gem-marking-templates';
UPDATE products SET blurb = 'Covington Rociprolap Nylon Bearings are a set of 12 precision nylon ball bearings for Rociprolap machines.', features = '["Set of 12 precision nylon ball bearings", "For Rociprolap machines"]', included = '[]', specs = '{}', warranty = NULL WHERE id = 'covington-rociprolap-nylon-bearings';
UPDATE products SET blurb = 'The Estwing Big Blue Geo Paleo Pick is a hoe-style pick with a pointed end on one side and a chiseled end on the other.

It is forged from solid American steel, has a powder-coated finish and a textured vinyl grip, and is made in the USA. The head is 14 in long, overall length is 25-1/2 in and it weighs 4 lb.', features = '["Hoe pick configuration", "Solid American steel", "Pointed end and chiseled end", "Powder coated finish", "Textured vinyl grip", "Made in the USA"]', included = '[]', specs = '{"Head length": "14\\"", "Overall length": "25-1/2\\"", "Weight": "4 lb"}', warranty = NULL WHERE id = 'estwing-big-blue-geo-paleo-pick';
UPDATE products SET blurb = 'Estwing Rock Picks are one-piece American steel picks with a pointed tip on one side and a smooth face on the other.

They have a blue shock-reduction grip and are made in the USA. Choose 14 oz, 22 oz or 22 oz long.', features = '["Solid American steel", "One piece construction", "Pointed tip and smooth face", "Blue Shock Reduction Grip", "Made in the USA"]', included = '[]', specs = '{"Weights available": "14 oz, 22 oz, 22 oz Long"}', warranty = NULL WHERE id = 'estwing-rock-picks';
UPDATE products SET blurb = 'The Estwing Crack Hammer is a one-piece American steel hammer with fully polished faces and a blue UV coating.

The blue shock-reduction grip softens impact, and it is made in the USA. Weights are 2 lb, 3 lb and 4 lb.', features = '["Solid American steel", "One piece construction", "Fully polished faces", "Blue UV coating", "Blue Shock Reduction Grip", "Made in the USA"]', included = '[]', specs = '{"Weights available": "2 lb, 3 lb, 4 lb"}', warranty = NULL WHERE id = 'estwing-crack-hammer';
UPDATE products SET blurb = 'The Covington Single Gallon Rolling Rock Tumbler holds a 12 lb load in a solid LLDPE barrel with a cast aluminum lid.

A 1/12 hp motor turns it on 1/2 in steel support bars with nylon bearings, in a powder-coated aluminum frame made in the USA.', features = '["Powder coated aluminum construction", "1/2\\" steel support bars", "Nylon bearings", "Solid LLDPE barrel with cast aluminum lid", "Made in USA"]', included = '[]', specs = '{"Capacity": "12 lb", "Motor": "1/12 hp"}', warranty = NULL WHERE id = 'covington-single-gallon-rolling-rock-tumbler';
UPDATE products SET blurb = 'Where to Find Gold in Northern California by Jim Klein covers prospecting techniques and equipment, as well as old mines and ghost towns.', features = '["Prospecting techniques and equipment", "Old mines and ghost towns", "By Jim Klein"]', included = '[]', specs = '{"Author": "Jim Klein"}', warranty = NULL WHERE id = 'where-to-find-gold-in-northern-california';
UPDATE products SET blurb = 'The Rockhound\'s Handbook by James R. Mitchell is a revised, expanded edition of a guide for people who collect rocks and minerals.', features = '["Revised expanded edition"]', included = '[]', specs = '{"Author": "James R. Mitchell"}', warranty = NULL WHERE id = 'the-rockhound-s-handbook';
